import { useEffect, useState } from 'react';
import { Button, Checkbox, FormControlLabel, MenuItem, Stack, Tab, Tabs, TextField } from '@mui/material';
import { api } from '../services/api';
import type { ChampionshipEvent, Competition, EventCompetitionMapping } from '../types';
import { ContentCard, OpsButton, SectionHeader } from '../design-system';

const emptyEvent = { name: '', year: new Date().getFullYear(), active: true };
export function AdministrationEvents() {
  const [events,setEvents]=useState<ChampionshipEvent[]>([]), [selectedId,setSelectedId]=useState('');
  const [selected,setSelected]=useState<ChampionshipEvent|null>(null), [competitions,setCompetitions]=useState<Competition[]>([]);
  const [tab,setTab]=useState(0), [form,setForm]=useState<Partial<ChampionshipEvent>>(emptyEvent), [addId,setAddId]=useState(''), [copyId,setCopyId]=useState('');
  const loadList=async()=>{const rows=await api.getAdminEvents();setEvents(rows);setSelectedId(value=>value||rows[0]?.id||'');};
  useEffect(()=>{void Promise.all([loadList(),api.getCompetitions().then(setCompetitions)]);},[]);
  useEffect(()=>{if(selectedId) void api.getAdminEvent(selectedId).then(value=>{setSelected(value);setForm(value);});},[selectedId]);
  const reload=async()=>{await loadList();if(selectedId)setSelected(await api.getAdminEvent(selectedId));};
  const save=async()=>{if(selected)await api.updateChampionshipEvent(selected.id,form);else {const created=await api.createChampionshipEvent(form);setSelectedId(created.id);}await reload();};
  const editMapping=async(mapping:EventCompetitionMapping,patch:Partial<EventCompetitionMapping>)=>{await api.updateEventCompetition(selectedId,mapping.id,patch);await reload();};
  return <div className="grid gap-4 lg:grid-cols-[16rem_1fr]">
    <ContentCard className="p-3"><OpsButton className="mb-3 w-full" onClick={()=>{setSelected(null);setSelectedId('');setForm(emptyEvent);setTab(0);}}>Event anlegen</OpsButton>{events.map(event=><button className={`mb-1 w-full rounded-lg p-3 text-left ${event.id===selectedId?'bg-[var(--ops-tone-primary-surface)]':'bg-[var(--ops-surface)]'}`} key={event.id} onClick={()=>setSelectedId(event.id)}><b>{event.name}</b><div className="text-xs text-[var(--ops-text-muted)]">{event.active?'Aktiv':'Inaktiv'}</div></button>)}</ContentCard>
    <ContentCard className="p-5"><Tabs value={tab} onChange={(_,value)=>setTab(value)}><Tab label="Allgemein"/><Tab label="Competition Mapping" disabled={!selected}/></Tabs>
      {tab===0&&<Stack spacing={2} sx={{pt:3,maxWidth:520}}><TextField required label="Name" value={form.name||''} onChange={e=>setForm({...form,name:e.target.value})}/><TextField type="number" label="Jahr" value={form.year||''} onChange={e=>setForm({...form,year:Number(e.target.value)})}/><TextField label="FIS Event ID" value={form.fisEventId||''} onChange={e=>setForm({...form,fisEventId:e.target.value})}/><TextField label="Sector Code" value={form.sectorCode||''} onChange={e=>setForm({...form,sectorCode:e.target.value})}/><FormControlLabel control={<Checkbox checked={form.active??true} onChange={e=>setForm({...form,active:e.target.checked})}/>} label="Aktiv"/><Button variant="contained" disabled={!form.name?.trim()} onClick={save}>Speichern</Button></Stack>}
      {tab===1&&selected&&<div className="pt-4"><SectionHeader title="Competition Mapping" subtitle="Eventabhängige FIS-Codes; Stammdaten bleiben global."/><div className="my-4 flex flex-wrap gap-2"><TextField select size="small" label="Competition hinzufügen" value={addId} onChange={e=>setAddId(e.target.value)} sx={{minWidth:240}}>{competitions.filter(c=>!selected.competitionMappings?.some(m=>m.competitionId===c.id)).map(c=><MenuItem key={c.id} value={c.id}>{c.displayName} · {c.gender}</MenuItem>)}</TextField><Button disabled={!addId} onClick={async()=>{const c=competitions.find(x=>x.id===addId)!;await api.addEventCompetition(selected.id,{competitionId:c.id,officialName:c.name,fisCodex:c.code,importCode:c.importCode,active:true});setAddId('');await reload();}}>Hinzufügen</Button><TextField select size="small" label="Mappings kopieren aus" value={copyId} onChange={e=>setCopyId(e.target.value)} sx={{minWidth:220}}>{events.filter(e=>e.id!==selected.id).map(e=><MenuItem key={e.id} value={e.id}>{e.name}</MenuItem>)}</TextField><Button disabled={!copyId} onClick={async()=>{await api.copyEventMappings(selected.id,copyId);await reload();}}>Kopieren</Button></div>
        <div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr>{['Display Name','Sport','Gender','Quota Discipline','Official Name','Codex','Import Code','Team','Aktiv'].map(x=><th className="p-2 text-left" key={x}>{x}</th>)}</tr></thead><tbody>{selected.competitionMappings?.map(m=><tr className="border-t border-[var(--ops-divider)]" key={m.id}><td>{m.displayName}</td><td>{m.sport}</td><td>{m.gender}</td><td>{m.quotaDiscipline}</td><td><TextField size="small" value={m.officialName} onChange={e=>setSelected({...selected,competitionMappings:selected.competitionMappings?.map(x=>x.id===m.id?{...x,officialName:e.target.value}:x)})} onBlur={e=>editMapping(m,{officialName:e.target.value})}/></td><td><TextField size="small" value={m.fisCodex} onChange={e=>setSelected({...selected,competitionMappings:selected.competitionMappings?.map(x=>x.id===m.id?{...x,fisCodex:e.target.value}:x)})} onBlur={e=>editMapping(m,{fisCodex:e.target.value})}/></td><td><TextField size="small" value={m.importCode} onChange={e=>setSelected({...selected,competitionMappings:selected.competitionMappings?.map(x=>x.id===m.id?{...x,importCode:e.target.value}:x)})} onBlur={e=>editMapping(m,{importCode:e.target.value})}/></td><td>{m.teamCompetition?'Ja':'Nein'}</td><td><Checkbox checked={m.active} onChange={e=>editMapping(m,{active:e.target.checked})}/></td></tr>)}</tbody></table></div>
      </div>}
    </ContentCard>
  </div>;
}
