import { type CSSProperties, type ReactNode, useEffect, useMemo, useRef, useState } from 'react';
import { useSearchParams } from 'react-router';
import { Dialog, DialogContent, DialogTitle } from '@mui/material';
import { AlertTriangle, CheckCircle, ChevronRight, Clock3, FileCheck2, FileText, Loader2, RefreshCcw, Upload, Users } from 'lucide-react';

import { api } from '../services/api';
import type { DispositionImpactCategory, FisImportIssue, FisImportPreview } from '../types';
import { IMPORT_SESSION_STATUS, type ImportSession } from '../data/importSessions';
import { ContentCard, EmptyState, InfoPanel, OpsButton, PageHeader, PageLayout, SectionHeader, StatusChip } from '../design-system';
import { MetricCard } from '../design-system/components/cards';
import { ImportQueue } from './ImportQueue';
import { buildOperationsTask, OperationsDecisionDialog, OperationsTaskRow, type OperationsTask } from './OperationsDecisionDialog';

const REQUIRED_FILE_HINTS = ['ENTRIES-LIST', 'ENTRIES-ROOM-LIST-DETAILED'];
const workflowSteps = ['Entwurf', 'Technisch geprüft', 'Fachlich geprüft', 'Warten auf Nation', 'Erneut prüfen', 'Freigegeben', 'Importiert'];
const theme = { '--ops-background':'#111d2e','--ops-surface':'#1a2a40','--ops-surface-raised':'#21334c','--ops-surface-elevated':'#2a3e59','--ops-surface-overlay':'#344b67','--ops-border':'#4b6380','--ops-divider':'#405773','--ops-text-muted':'#b7c4d4' } as CSSProperties;
type Detail = { title: string; subtitle?: string; issues?: FisImportIssue[]; rows?: string[][]; headers?: string[]; records?: Array<Record<string, unknown>>; category?: DispositionImpactCategory };

export function DataImport() {
  const [searchParams] = useSearchParams();
  const detailScrollRef = useRef<HTMLDivElement>(null);
  const [selected, setSelected] = useState<ImportSession | null>(null);
  const [sessions, setSessions] = useState<ImportSession[]>([]);
  const [files, setFiles] = useState<File[]>([]);
  const [preview, setPreview] = useState<FisImportPreview | null>(null);
  const [loading, setLoading] = useState(false), [confirming, setConfirming] = useState(false);
  const [error, setError] = useState<string | null>(null), [success, setSuccess] = useState<string | null>(null);
  const [detail, setDetail] = useState<Detail | null>(null);
  const [activeTask, setActiveTask] = useState<OperationsTask | null>(null);
  const [savingTask, setSavingTask] = useState(false);
  const quotaWarnings = useMemo(() => preview?.warnings.filter(i => i.code.startsWith('QUOTA_')) ?? [], [preview]);
  const otherWarnings = useMemo(() => preview?.warnings.filter(i => !i.code.startsWith('QUOTA_')) ?? [], [preview]);
  const statusStep: Partial<Record<ImportSession['status'],number>> = {DRAFT:0,TECHNICALLY_REVIEWED:1,PREVIEW_CREATED:1,PROFESSIONALLY_REVIEWED:2,READY_FOR_IMPORT:2,WAITING_FOR_NATION:3,NATION_CLARIFICATION:3,NEW_LIST_RECEIVED:4,RECHECK_REQUIRED:4,APPROVED:5,IMPORTED:6};
  const currentStep = selected ? statusStep[selected.status] ?? 0 : files.length ? 0 : 0;

  const refreshSessions = async () => setSessions(await api.getImportSessions());
  useEffect(() => { (async () => { try { const loaded = await api.getImportSessions(); setSessions(loaded); const requested = searchParams.get('sessionId'); const match = requested && loaded.find(session => session.id === requested); if (match) await selectSession(match); } catch(e) { setError(e instanceof Error ? e.message : 'Sessions konnten nicht geladen werden'); } })(); }, []);
  const selectSession = async (session: ImportSession) => { const full = await api.getImportSession(session.id); setSelected(full); setPreview(full.preview ?? null); setFiles([]); setSuccess(null); detailScrollRef.current?.scrollTo({ top: 0 }); };
  const createSession = () => { setSelected(null); setPreview(null); setSuccess(null); setError(null); detailScrollRef.current?.scrollTo({ top: 0 }); };
  const handleFiles = (incoming: FileList | File[] | null | undefined) => {
    if (!incoming) return; const accepted = Array.from(incoming).filter(f => /\.xlsx?$/i.test(f.name));
    if (!accepted.length) { setError('Bitte Excel-Dateien (.xlsx, .xls) hochladen.'); return; }
    setFiles([...new Map(accepted.map(f => [f.name.toLowerCase(), f])).values()]); setPreview(null); setSuccess(null); setError(null);
  };
  const cancel = () => { setFiles([]); setPreview(null); setError(null); setSuccess(null); const input = document.getElementById('fis-files-input') as HTMLInputElement | null; if (input) input.value = ''; };
  const runPreview = async () => { if (files.length < 2) return; setLoading(true); setError(null); setSuccess(null); setPreview(null); try { const result = await api.previewFisImport(files, !selected, selected?.id); setPreview(result); if (result.session) { setSelected({...result.session, preview: result}); setFiles([]); await refreshSessions(); } } catch (e) { setError(e instanceof Error ? e.message : 'Preview fehlgeschlagen'); } finally { setLoading(false); } };
  const approve = async () => { if (!selected) return; setConfirming(true); setError(null); try { const updated = await api.approveImportSession(selected.id); setSelected(updated); await refreshSessions(); } catch(e) { setError(e instanceof Error ? e.message : 'Freigabe fehlgeschlagen'); } finally { setConfirming(false); } };
  const confirm = async () => { if (!selected || selected.status !== 'APPROVED') return; setConfirming(true); setError(null); try { const result = await api.importSession(selected.id); setSuccess(`Import erfolgreich: ${result.summary.peopleCreated} neu, ${result.summary.peopleUpdated} aktualisiert. Bestehende Dispositionen wurden nicht verändert.`); setSelected(await api.getImportSession(selected.id)); await refreshSessions(); } catch (e) { setError(e instanceof Error ? e.message : 'Import fehlgeschlagen'); } finally { setConfirming(false); } };
  const saveTask = async (decision: 'APPROVED'|'REJECTED'|'LATER', comment: string) => {
    if (!selected || !activeTask) return;
    if (decision === 'LATER') { setActiveTask(null); return; }
    setSavingTask(true); setError(null);
    try { const updated = await api.decideImportTask(selected.id, activeTask.approval.id, decision, comment); setSelected(updated); setPreview(updated.preview ?? null); setActiveTask(null); await refreshSessions(); }
    catch (e) { setError(e instanceof Error ? e.message : 'Entscheidung konnte nicht gespeichert werden'); }
    finally { setSavingTask(false); }
  };

  const openIssues = (title: string, issues: FisImportIssue[]) => setDetail({ title, subtitle: `${issues.length} betroffene Prüfhinweise`, issues, category: issues.length && issues.every(issue => issue.code.startsWith('QUOTA_')) ? 'quotaAffected' : undefined });
  const peopleRows = preview?.people.map(p => [`${p.firstname} ${p.lastname}`, p.nationCode, p.discipline || '—', p.function || '—', p.operation]) ?? [];
  const roomRows = preview?.rooms.map(r => [r.person1Name, r.person2Name || '—', r.roomType, [r.checkInDate, r.checkOutDate].filter(Boolean).join(' → ') || '—']) ?? [];

  return <div style={theme} className="-m-6 h-[calc(100vh-0px)] min-h-[720px] bg-[var(--ops-background)] p-6 text-[var(--ops-text)]">
    <PageLayout className="flex h-full min-h-0 flex-col gap-5 space-y-0">
      <PageHeader eyebrow="Operations Center" title="Import Center" subtitle="FIS-Import Sessions prüfen, entscheiden und kontrolliert abschließen." meta={selected ? <><StatusChip tone={selected.errors ? 'error' : selected.warnings ? 'warning' : 'success'}>{IMPORT_SESSION_STATUS[selected.status]}</StatusChip><span className="text-sm text-[var(--ops-text-muted)]">IS-{selected.id} · {selected.nation} · {selected.discipline}</span></> : <StatusChip tone="primary">Neue Import Session</StatusChip>} />
      <div className="flex min-h-0 flex-1 flex-col gap-5 xl:flex-row">
        <ImportQueue sessions={sessions} selectedId={selected?.id ?? null} isCreating={!selected} onCreate={createSession} onSelect={selectSession} />
        <ContentCard surface="raised" className="min-h-0 flex-1 overflow-hidden">
          <div ref={detailScrollRef} className="h-full overflow-y-auto">
            {!selected ? <NewSessionWorkspace files={files} preview={preview} loading={loading} confirming={confirming} error={error} success={success} currentStep={currentStep} onFiles={handleFiles} onPreview={runPreview} onConfirm={confirm} onCancel={cancel} /> : <>
            <div className="sticky top-0 z-10 flex flex-wrap items-start justify-between gap-4 border-b border-[var(--ops-divider)] bg-[var(--ops-surface-raised)] p-5">
              <div><SectionHeader title="Session" /><h2 className="mt-2 text-2xl font-extrabold">{selected.nation} · {selected.discipline}</h2><p className="text-sm text-[var(--ops-text-muted)]">{selected.uploadedAt} · {selected.uploadedBy} · Version {selected.version}</p></div>
              <div className="flex gap-2"><OpsButton onClick={approve} disabled={!preview?.isValid || selected.approvals.some(a => a.decision !== 'APPROVED') || !['PROFESSIONALLY_REVIEWED','READY_FOR_IMPORT','WAITING_FOR_NATION','NATION_CLARIFICATION','NEW_LIST_RECEIVED'].includes(selected.status)}>Freigeben</OpsButton><OpsButton onClick={confirm} disabled={selected.status !== 'APPROVED' || confirming} className="border-[var(--ops-tone-success-border)] bg-[var(--ops-tone-success-surface)]"><CheckCircle className="mr-2 inline h-4 w-4" />Importieren</OpsButton></div>
            </div>
            <div className="space-y-5 p-5">
              <div className="grid grid-cols-2 gap-3 lg:grid-cols-5"><MetricCard label="Status" value={IMPORT_SESSION_STATUS[selected.status]} helper="Aktueller Schritt" tone="primary" /><MetricCard label="Personen" value={preview?.summary.people.total ?? '—'} helper="Importumfang" /><MetricCard label="Neu" value={preview?.summary.people.wouldCreate ?? '—'} helper="Athleten & Officials" tone="success" /><MetricCard label="Warnungen" value={preview?.summary.validation.warningCount ?? selected.warnings} helper="zu prüfen" tone="warning" /><MetricCard label="Fehler" value={preview?.summary.validation.errorCount ?? selected.errors} helper="blockierend" tone="error" /></div>
              <Workflow current={currentStep} />
              <div className="grid items-start gap-5 lg:grid-cols-2"><UploadCard files={files} onChange={handleFiles}/><ContentCard surface="elevated" className="p-4"><SectionHeader title="Neue Version" subtitle="Die bestehende Session bleibt erhalten"/><p className="mt-3 text-sm text-[var(--ops-text-muted)]">Eine neue Meldeliste dieser Nation wird als Version {selected.version + 1} geprüft. Frühere Versionen bleiben in der Historie nachvollziehbar.</p><div className="mt-4 flex gap-2"><OpsButton onClick={runPreview} disabled={files.length<2||loading}>{loading?<Loader2 className="mr-2 inline h-4 w-4 animate-spin"/>:<FileCheck2 className="mr-2 inline h-4 w-4"/>}Version prüfen</OpsButton><OpsButton onClick={cancel} disabled={!files.length}>Abbrechen</OpsButton></div></ContentCard></div>
              {error && <InfoPanel tone="error" title="Aktion fehlgeschlagen">{error}</InfoPanel>}{success && <InfoPanel tone="success" title="Import abgeschlossen">{success}</InfoPanel>}
              <div className="grid items-start gap-5 lg:grid-cols-2"><TaskList session={selected} onOpen={setActiveTask}/><ImpactList preview={preview} onOpen={setDetail}/></div>
              <ProblemList preview={preview} fallback={selected} quota={quotaWarnings} others={otherWarnings} onOpen={openIssues}/>
              <SessionHistory session={selected}/>
              <ContentCard surface="elevated" className="p-4"><SectionHeader title="Preview" subtitle="Details werden erst auf Auswahl geöffnet"/><div className="mt-4 grid gap-3 sm:grid-cols-2"><SummaryRow label="Personen-Vorschau" count={peopleRows.length} onClick={() => setDetail({title:'Personen-Vorschau', rows:peopleRows, headers:['Name','Nation','Disziplin','Funktion','Aktion']})}/><SummaryRow label="Zimmer-Vorschau" count={roomRows.length} onClick={() => setDetail({title:'Zimmer-Vorschau', rows:roomRows, headers:['Person 1','Person 2','Zimmer','Aufenthalt']})}/></div></ContentCard>
            </div>
            </>}
          </div>
        </ContentCard>
      </div>
    </PageLayout>
    <DetailDialog detail={detail} onClose={() => setDetail(null)} />
    <OperationsDecisionDialog task={activeTask} saving={savingTask} onClose={() => setActiveTask(null)} onSave={saveTask}/>
  </div>;
}

function NewSessionWorkspace({files,preview,loading,confirming,error,success,currentStep,onFiles,onPreview,onConfirm,onCancel}:{files:File[];preview:FisImportPreview|null;loading:boolean;confirming:boolean;error:string|null;success:string|null;currentStep:number;onFiles:(files:FileList|null)=>void;onPreview:()=>void;onConfirm:()=>void;onCancel:()=>void}) { return <>
  <div className="sticky top-0 z-10 flex flex-wrap items-start justify-between gap-4 border-b border-[var(--ops-divider)] bg-[var(--ops-surface-raised)] p-5"><div><SectionHeader title="Session-Erstellung"/><h2 className="mt-2 text-2xl font-extrabold">Neue Import Session</h2><p className="text-sm text-[var(--ops-text-muted)]">FIS-Dateien hochladen und vor dem Import gemeinsam prüfen.</p></div><div className="flex gap-2"><OpsButton onClick={onPreview} disabled={files.length<2||loading}>{loading?<Loader2 className="mr-2 inline h-4 w-4 animate-spin"/>:<FileCheck2 className="mr-2 inline h-4 w-4"/>}Preview prüfen</OpsButton><OpsButton onClick={onConfirm} disabled={true} className="border-[var(--ops-tone-success-border)] bg-[var(--ops-tone-success-surface)]"><CheckCircle className="mr-2 inline h-4 w-4"/>Importieren</OpsButton></div></div>
  <div className="space-y-5 p-5"><Workflow current={currentStep}/><div className="grid items-start gap-5 lg:grid-cols-2"><UploadCard files={files} onChange={onFiles}/><ContentCard surface="elevated" className="p-4"><SectionHeader title="Uploadinformationen" subtitle="Dateien für die neue Session"/><div className="mt-4 space-y-2">{files.length?files.map(file=><div key={file.name} className="flex items-center justify-between rounded-lg bg-[var(--ops-surface)] p-3 text-sm"><span className="flex min-w-0 items-center gap-2"><FileText className="h-4 w-4 shrink-0"/><span className="truncate">{file.name}</span></span><span className="font-mono text-xs text-[var(--ops-text-muted)]">{(file.size/1024).toFixed(1)} KB</span></div>):<EmptyState title="Noch keine Dateien" description="Beide FIS-Dateien gemeinsam hochladen."/>}</div><div className="mt-3"><OpsButton onClick={onCancel} disabled={!files.length&&!preview}><RefreshCcw className="mr-2 inline h-4 w-4"/>Upload zurücksetzen</OpsButton></div></ContentCard></div>{error&&<InfoPanel tone="error" title="Aktion fehlgeschlagen">{error}</InfoPanel>}{success&&<InfoPanel tone="success" title="Import abgeschlossen">{success}</InfoPanel>}{preview&&<div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><MetricCard label="Personen" value={preview.summary.people.total} helper="Importumfang"/><MetricCard label="Neu" value={preview.summary.people.wouldCreate} helper="werden angelegt" tone="success"/><MetricCard label="Warnungen" value={preview.summary.validation.warningCount} helper="zu prüfen" tone="warning"/><MetricCard label="Fehler" value={preview.summary.validation.errorCount} helper="blockierend" tone="error"/></div>}</div>
</>; }

function Workflow({current}:{current:number}) { return <ContentCard surface="elevated" className="p-4"><SectionHeader title="Workflow"/><ol className="mt-4 grid grid-cols-3 gap-2 lg:grid-cols-7">{workflowSteps.map((s,i)=><li key={s} className={`rounded-lg border p-2.5 ${i<=current?'border-[var(--ops-tone-primary-border)] bg-[var(--ops-tone-primary-surface)]':'border-[var(--ops-border)] bg-[var(--ops-surface)]'}`}><span className="font-mono text-[10px] text-[var(--ops-text-subtle)]">0{i+1}</span><div className="text-xs font-bold">{s}</div></li>)}</ol></ContentCard>; }
function SessionHistory({session}:{session:ImportSession}) { return <ContentCard surface="elevated" className="p-4"><SectionHeader title="Historie" subtitle={`${session.versions?.length ?? 0} Version(en) · vollständiger Session-Verlauf`}/><div className="mt-4 space-y-3">{session.history?.length ? [...session.history].reverse().map(event=><div key={event.id} className="grid grid-cols-[auto_1fr] gap-3 border-b border-[var(--ops-divider)] pb-3"><Clock3 className="mt-0.5 h-4 w-4 text-[var(--ops-text-subtle)]"/><div><div className="flex flex-wrap justify-between gap-2"><span className="font-bold">{event.title}</span><span className="font-mono text-xs text-[var(--ops-text-subtle)]">{new Date(event.timestamp).toLocaleString('de-DE')} · {event.user}</span></div>{event.description&&<p className="mt-1 text-sm text-[var(--ops-text-muted)]">{event.description}</p>}</div></div>):<EmptyState title="Noch keine Historieneinträge" description="Versionen, Entscheidungen und Freigaben werden automatisch protokolliert."/>}</div></ContentCard>; }
function UploadCard({files,onChange}:{files:File[];onChange:(f:FileList|null)=>void}) { return <ContentCard surface="elevated" className="p-4"><SectionHeader title="Neue Import Session" subtitle="Beide Dateien in einem Schritt auswählen"/><label className="mt-4 block cursor-pointer rounded-xl border-2 border-dashed border-[var(--ops-border-strong)] bg-[var(--ops-surface)] p-6 text-center hover:bg-[var(--ops-tone-primary-surface)]"><input id="fis-files-input" type="file" accept=".xlsx,.xls" multiple className="hidden" onChange={e=>onChange(e.target.files)}/><Upload className="mx-auto h-8 w-8 text-[var(--ops-primary)]"/><p className="mt-2 font-bold">{files.length ? `${files.length} Datei(en) ausgewählt` : 'Dateien auswählen oder ablegen'}</p><p className="mt-1 text-xs text-[var(--ops-text-muted)]">{REQUIRED_FILE_HINTS.join(' + ')}</p></label></ContentCard>; }
function ProblemList({preview,fallback,quota,others,onOpen}:{preview:FisImportPreview|null;fallback:ImportSession;quota:FisImportIssue[];others:FisImportIssue[];onOpen:(t:string,i:FisImportIssue[])=>void}) { const blocking=preview?.errors??[]; const decisions=quota; const information=others; const entries=[['Information',information,preview?information.length:Math.max(0,fallback.warnings-1),'success'],['Entscheidung erforderlich',decisions,preview?decisions.length:Math.min(fallback.warnings,1),'warning'],['Blockierend',blocking,preview?blocking.length:fallback.errors,'error']] as const; return <ContentCard surface="elevated" className="p-4"><SectionHeader title="Prüfergebnis" subtitle="Ergebnisse nach fachlicher Bedeutung"/><div className="mt-4 space-y-2">{entries.map(([label,issues,count,tone])=><SummaryRow key={label} label={label} count={count} tone={tone} disabled={!preview || !issues.length} onClick={()=>onOpen(label,[...issues])}/>)}{entries.every(e=>e[2]===0)&&<InfoPanel tone="success" title="Keine Probleme">Die Session ist bereit für den Import.</InfoPanel>}</div></ContentCard>; }
function TaskList({session,onOpen}:{session:ImportSession;onOpen:(task:OperationsTask)=>void}) { const tasks=session.approvals.map(approval=>buildOperationsTask(session,approval)); const open=tasks.filter(task=>task.approval.decision==='PENDING').length; return <ContentCard surface="elevated" className="p-4"><SectionHeader title="Aufgaben" subtitle={`${open} offen · ${tasks.length-open} entschieden`} actions={<StatusChip tone={open?'warning':'success'}>{open?`${open} zu bearbeiten`:'Abgeschlossen'}</StatusChip>}/><div className="mt-4 space-y-2">{tasks.length?tasks.map(task=><OperationsTaskRow key={task.approval.id} task={task} onOpen={()=>onOpen(task)}/>):<EmptyState title="Keine offenen Entscheidungen" description="Aus der Prüfung wurden für diese Session keine Rücksprachen erzeugt."/>}</div></ContentCard>; }
const impactGroups: Array<{title:string; items:Array<[DispositionImpactCategory,string]>}> = [
  {title:'Personen',items:[['newAthletes','Neue Athleten'],['updatedAthletes','Aktualisierte Athleten'],['removedAthletes','Entfernte Athleten']]},
  {title:'Disposition',items:[['dispositionAffected','Bestehende Disposition betroffen']]},
  {title:'Regeln',items:[['quotaAffected','Quoten werden neu berechnet']]},
];
function ImpactList({preview,onOpen}:{preview:FisImportPreview|null;onOpen:(d:Detail)=>void}) { const categories=preview?.dispositionAnalysis?.categories; return <ContentCard surface="elevated" className="p-4"><SectionHeader title="Auswirkungen des Imports" subtitle="Informationen ohne Aktion oder Auswirkung auf die Freigabe"/><div className="mt-4 space-y-4">{impactGroups.map(group=><section key={group.title}><h3 className="mb-2 text-xs font-extrabold uppercase tracking-wider text-[var(--ops-text-subtle)]">{group.title}</h3><div className="space-y-2">{group.items.map(([key,label])=>{const impact=categories?.[key];return <SummaryRow key={key} label={label} count={impact?.count??0} tone="success" disabled={!impact?.count} onClick={()=>onOpen({title:label,subtitle:`${impact?.count??0} betroffene Datensätze · keine Aktion erforderlich`,records:impact?.records??[],category:key})}/>})}</div></section>)}</div></ContentCard>; }
function SummaryRow({label,count,tone='neutral',disabled,onClick}:{label:string;count:number;tone?:'neutral'|'success'|'warning'|'error';disabled?:boolean;onClick:()=>void}) { return <button type="button" disabled={disabled} onClick={onClick} className="flex w-full items-center justify-between rounded-lg border border-[var(--ops-border)] bg-[var(--ops-surface)] px-3 py-2.5 text-left transition hover:border-[var(--ops-border-strong)] hover:bg-[var(--ops-surface-overlay)] disabled:cursor-default disabled:opacity-70"><span className="flex items-center gap-2 text-sm font-bold">{tone==='error'?<AlertTriangle className="h-4 w-4 text-[var(--ops-error)]"/>:tone==='success'?<CheckCircle className="h-4 w-4 text-[var(--ops-success)]"/>:<Users className="h-4 w-4 text-[var(--ops-text-subtle)]"/>}{label}</span><span className="flex items-center gap-2"><StatusChip tone={tone}>{count}</StatusChip><ChevronRight className="h-4 w-4 text-[var(--ops-text-subtle)]"/></span></button>; }
const detailLabels:Record<string,string>={athlete:'Athlet',person:'Athlet',name:'Athlet',nation:'Nation',nationCode:'Nation',discipline:'Disziplin',hotel:'Hotel',roomNumber:'Zimmer',room:'Zimmer',roomType:'Zimmertyp',roommates:'Zimmerpartner',reason:'Grund der Änderung',status:'Status',impact:'Auswirkung',gender:'Gender',currentQuota:'Aktuelle Quote',allowedQuota:'Erlaubte Quote',additionalCostPerNight:'Mehrkosten pro Nacht',approvalRequired:'Genehmigung erforderlich',oldPartners:'Zimmerpartner',newPartners:'Zimmerpartner',changes:'Änderungen',row:'Zeile',firstname:'Vorname',lastname:'Nachname',sharedWithName:'Zimmerpartner',sharedWithNationcode:'Nation',value:'Wert',column:'Spalte'};
function displayValue(value:unknown):string { if(value===null||value===undefined||value==='') return 'Noch zu ermitteln'; if(Array.isArray(value)) return value.length?value.map(displayValue).join(', '):'kein Partner'; if(typeof value==='boolean') return value?'Ja':'Nein'; if(typeof value==='object'){const object=value as Record<string,unknown>;if('arrival' in object||'departure' in object)return `${displayValue(object.arrival)}–${displayValue(object.departure)}`;return Object.entries(object).map(([key,item])=>`${detailLabels[key]??key}: ${displayValue(item)}`).join(' · ')} return String(value); }
const impactCopy:Partial<Record<DispositionImpactCategory,string>>={newAthletes:'Neue Person erkannt; sie wird beim Import angelegt',updatedAthletes:'Stammdaten werden beim Import aktualisiert',removedAthletes:'Person fehlt in der neuen Meldung',hotelAssignmentAffected:'Bestehende Disposition betroffen',roommateAffected:'Bestehende Disposition betroffen',stayChanged:'Bestehende Disposition betroffen',roomRequirementChanged:'Bestehende Disposition betroffen',quotaAffected:'Quoten werden neu berechnet',approvalRequired:'Fachliche Freigabe erforderlich',additionalCostsPossible:'Mehrkosten möglich',dispositionAffected:'Bestehende Disposition betroffen'};
const masterDataKeys=['athlete','person','name','nation','nationCode','discipline','gender','hotel','roomType','roomNumber','room','roommates','sharedWithName','oldPartners','newPartners','checkInDate','checkOutDate','arrivalDate','departureDate','stay'];
function RecordSection({title,children}:{title:string;children:ReactNode}) { return <section><h3 className="mb-2 text-xs font-extrabold uppercase tracking-wider text-[var(--ops-text-subtle)]">{title}</h3><div className="rounded-xl border border-[var(--ops-border)] bg-[var(--ops-surface-elevated)] p-4">{children}</div></section>; }
function ImpactRecord({record,category}:{record:Record<string,unknown>;category?:DispositionImpactCategory}) {
  const changes=Array.isArray(record.changes)?record.changes as Array<Record<string,unknown>>:('old' in record||'new' in record)?[{field:detailLabels[category==='roommateAffected'?'oldPartners':'roomType']??'Änderung',old:record.old??record.oldPartners,new:record.new??record.newPartners}]:[];
  const personData=masterDataKeys.flatMap(key=>record[key]!==undefined&&record[key]!==null&&record[key]!==''?[[key,record[key]] as [string,unknown]]:[]).filter(([key],index,all)=>!['person','name','nationCode','room'].includes(key)||!all.some(([other])=>({person:'athlete',name:'athlete',nationCode:'nation',room:'roomNumber'} as Record<string,string>)[key]===other));
  return <article className="space-y-4">
    <RecordSection title="1. Betroffene Person">{personData.length?<div className="grid gap-3 sm:grid-cols-2">{personData.map(([key,value])=><div key={key}><div className="text-xs font-bold text-[var(--ops-text-subtle)]">{detailLabels[key]??key}</div><div className="mt-0.5 font-semibold">{displayValue(value)}</div></div>)}</div>:<p className="text-sm text-[var(--ops-text-muted)]">Die Änderung betrifft die gemeldete Gruppe.</p>}</RecordSection>
    <RecordSection title="2. Änderung">{changes.length?<div className="space-y-3">{changes.map((change,index)=><div key={index}><div className="mb-2 text-sm font-bold">{displayValue(change.field)}</div><div className="grid gap-2 sm:grid-cols-2"><div className="rounded-lg bg-[var(--ops-background)] p-3"><div className="text-xs font-bold uppercase text-[var(--ops-text-subtle)]">Alt</div><div className="mt-1 font-semibold">{displayValue(change.old)}</div></div><div className="rounded-lg bg-[var(--ops-background)] p-3"><div className="text-xs font-bold uppercase text-[var(--ops-text-subtle)]">Neu</div><div className="mt-1 font-semibold">{displayValue(change.new)}</div></div></div></div>)}</div>:<p className="text-sm">{displayValue(record.reason??'Datensatz im Import geändert')}</p>}</RecordSection>
    <RecordSection title="3. Auswirkungen"><div className="flex items-center gap-2 font-bold"><CheckCircle className="h-5 w-5 text-[var(--ops-success)]"/>{category?impactCopy[category]:'Keine Auswirkungen'}</div></RecordSection>
    <InfoPanel tone="success" title="Information">Keine Aktion erforderlich. Diese Auswirkung blockiert den Import nicht.</InfoPanel>
  </article>;
}
const issueCopy:Record<string,{message:string;causes?:string[];action:string}>={
  ROOM_PERSON_NOT_FOUND:{message:'Neue Person erkannt.',action:'Die Person wird beim Import neu angelegt.'},
  ROOM_PARTNER_NOT_FOUND:{message:'Neue Person als Zimmerpartner erkannt.',action:'Die Person wird beim Import neu angelegt.'},
  ROOM_INVALID_ARRIVAL_DATE:{message:'Das Anreisedatum ist nicht lesbar.',action:'Importdaten korrigieren'}, ROOM_INVALID_DEPARTURE_DATE:{message:'Das Abreisedatum ist nicht lesbar.',action:'Importdaten korrigieren'},
  ROOM_INVALID_STAY_RANGE:{message:'Die Abreise liegt vor der Anreise.',action:'Importdaten korrigieren'}, ROOM_DAY_VALUE_NOT_NUMERIC:{message:'Die Zimmerbelegung enthält einen ungültigen Wert.',action:'Keine Aktion erforderlich'}, ROOM_NO_DAY_OVERLAP:{message:'Der Aufenthalt liegt außerhalb des gemeldeten Zeitraums.',action:'Keine Aktion erforderlich'},
};
function IssueRecord({issue,isInformation,isDecision}:{issue:FisImportIssue;isInformation:boolean;isDecision:boolean}) { const copy=issueCopy[issue.code]; const detected=/discipline/i.test(issue.code); return <article className="space-y-4"><RecordSection title="1. Betroffene Person"><div className="grid gap-3 sm:grid-cols-2">{Object.entries(issue.details??{}).filter(([key])=>['firstname','lastname','nationCode','discipline','gender','hotel','roomType','sharedWithName','sharedWithNationcode','arrivalDate','departureDate'].includes(key)).map(([key,value])=><div key={key}><div className="text-xs font-bold text-[var(--ops-text-subtle)]">{detailLabels[key]??key}</div><div className="font-semibold">{displayValue(value)}</div></div>)}</div></RecordSection><RecordSection title="2. Änderung"><p className="font-bold">{detected?'Disziplin automatisch erkannt':copy?.message??'Die Importdatei enthält einen Prüfhinweis.'}</p>{detected&&<p className="mt-2 text-sm text-[var(--ops-text-muted)]">Erkannt: {displayValue(issue.details?.discipline??issue.details?.value)} · Quelle: Dateiname</p>}</RecordSection><RecordSection title="3. Auswirkungen"><div className="flex gap-2 font-bold">{isInformation?<CheckCircle className="h-5 w-5 text-[var(--ops-success)]"/>:<AlertTriangle className="h-5 w-5 text-[var(--ops-warning)]"/>}{isInformation?'Keine Aktion notwendig':isDecision?'Fachliche Entscheidung erforderlich':'Import ist bis zur Korrektur blockiert'}</div>{!copy&&!detected&&<details className="mt-3 text-sm"><summary className="cursor-pointer font-bold">Technische Details</summary><p className="mt-2 text-[var(--ops-text-muted)]">{issue.message}</p></details>}</RecordSection><InfoPanel tone={isInformation?'success':'info'} title="Empfohlene Aktion">{isInformation?'Keine Aktion erforderlich':copy?.action??'Importdaten prüfen'}</InfoPanel></article>; }
function DetailDialog({detail,onClose}:{detail:Detail|null;onClose:()=>void}) {
  const isInformation=detail?.title==='Information', isDecision=detail?.title==='Entscheidung erforderlich';
  return (
    <Dialog open={Boolean(detail)} onClose={onClose} fullWidth maxWidth="lg">
      <DialogTitle>{detail?.title}<div className="text-sm font-normal text-[var(--ops-text-muted)]">{detail?.subtitle}</div></DialogTitle>
      <DialogContent dividers>
        <div className="space-y-6">{detail?.records?.map((record,i)=><ImpactRecord key={i} record={record} category={detail.category}/>)}{detail?.issues?.map((issue,i)=><IssueRecord key={`${issue.code}-${i}`} issue={issue} isInformation={Boolean(isInformation)} isDecision={Boolean(isDecision)}/>)}</div>
        {detail?.rows&&detail.rows.length>0&&<div className="mt-3 overflow-x-auto"><table className="w-full text-sm"><thead><tr>{detail.headers?.map(h=><th key={h} className="border-b border-[var(--ops-divider)] px-3 py-2 text-left text-xs uppercase text-[var(--ops-text-subtle)]">{h}</th>)}</tr></thead><tbody>{detail.rows.slice(0,50).map((r,i)=><tr key={i} className="border-b border-[var(--ops-divider)]">{r.map((c,j)=><td key={j} className="px-3 py-2">{c}</td>)}</tr>)}</tbody></table></div>}
        {detail&&!detail.issues?.length&&!detail.rows?.length&&!detail.records?.length&&<EmptyState title="Keine betroffenen Datensätze" description="Für diese Session liegen keine Detailänderungen vor."/>}
      </DialogContent>
    </Dialog>
  );
}
