import { useEffect, useMemo, useRef, useState } from 'react';
import { Button, CircularProgress, Dialog, DialogActions, DialogContent, DialogTitle, Stack, TextField } from '@mui/material';
import { BedDouble, Building2, DoorOpen, Pencil, Plus, Search, Trash2, Users } from 'lucide-react';
import { clsx } from 'clsx';
import { usePermissions } from '../auth/AuthProvider';
import { api } from '../services/api';
import type { Hotel, HotelRoomInventory, RoomBooking, RoomType } from '../types';
import { ContentCard, CrudDialog, EmptyState, InfoPanel, OpsButton, PageHeader, PageLayout, SectionHeader, StatusChip } from '../design-system';
import { READ_ONLY_TOOLTIP } from './PageLayout';
import { HotelContingentDialog } from './HotelContingentDialog';
import type { HotelContingentValues } from './HotelContingentValidation';
import { OperationsTimeline, type TimelineRowData } from './timeline';

type Tone = 'neutral' | 'primary' | 'success' | 'warning' | 'error' | 'info';
type Stats = { totalRooms:number; occupiedRooms:number; freeRooms:number; totalBeds:number; occupiedBeds:number; freeBeds:number; occupancy:number; status:string; tone:Tone; range:string };
const date = (v?:string) => v ? new Date(v).toLocaleDateString('de-DE') : 'offen';
const range = (hotel:Hotel) => { const inv=hotel.roomInventories||[]; if(!inv.length)return 'Kein Zeitraum'; return `${date(inv.map(i=>i.availableFrom).sort()[0])} – ${date(inv.map(i=>i.availableUntil).sort().at(-1))}`; };
function stats(hotel:Hotel, bookings:RoomBooking[], inventory?:HotelRoomInventory):Stats { const inv=inventory?[inventory]:(hotel.roomInventories||[]); const matching=bookings.filter(b=>b.hotel.id===hotel.id&&(!inventory||b.roomType.id===inventory.roomType.id)); const totalRooms=inv.reduce((s,i)=>s+i.roomCount,0), totalBeds=inv.reduce((s,i)=>s+i.roomCount*i.roomType.maxPersons,0), occupiedRooms=matching.length, occupiedBeds=matching.reduce((s,b)=>s+Math.max(b.occupants.length,b.countsAsSingle?1:0),0), occupancy=totalRooms?Math.min(100,occupiedRooms/totalRooms*100):0; const full=totalRooms>0&&occupiedRooms>=totalRooms, tight=occupancy>=85; return {totalRooms,occupiedRooms,freeRooms:Math.max(0,totalRooms-occupiedRooms),totalBeds,occupiedBeds,freeBeds:Math.max(0,totalBeds-occupiedBeds),occupancy,status:full?'Voll':tight?'Fast voll':'Verfügbar',tone:full?'error':tight?'warning':'success',range:inventory?`${date(inventory.availableFrom)} – ${date(inventory.availableUntil)}`:range(hotel)}; }
function Bar({value,tone}:{value:number;tone:Tone}) { return <div className="h-2 overflow-hidden rounded-full bg-[var(--ops-background)]"><div className={clsx('h-full rounded-full',tone==='error'?'bg-[var(--ops-error)]':tone==='warning'?'bg-[var(--ops-warning)]':'bg-[var(--ops-success)]')} style={{width:`${value}%`}} /></div>; }
function Metric({label,value,icon}:{label:string;value:number|string;icon:React.ReactNode}) { return <div className="rounded-[var(--ops-radius-lg)] bg-[var(--ops-surface-raised)] p-4"><div className="flex items-center gap-2 text-[11px] font-bold uppercase tracking-wider text-[var(--ops-text-subtle)]">{icon}{label}</div><div className="mt-2 text-2xl font-extrabold text-[var(--ops-text)]">{value}</div></div>; }

function HotelDialog({open,hotel,onClose,onSave}:{open:boolean;hotel:Hotel|null;onClose:()=>void;onSave:(v:{name:string;location:string;region:string})=>Promise<void>}) { const initial={name:hotel?.name||'',location:hotel?.location||'',region:hotel?.region||''}; const [form,setForm]=useState(initial),[saving,setSaving]=useState(false); useEffect(()=>{if(open)setForm(initial);},[open,hotel?.id]); return <CrudDialog open={open} title={hotel?'Hotel bearbeiten':'Hotel hinzufügen'} dirty={JSON.stringify(form)!==JSON.stringify(initial)} saving={saving} saveDisabled={!form.name.trim()} onClose={onClose} onSave={async()=>{setSaving(true);try{await onSave(form);onClose();}finally{setSaving(false);}}}><Stack spacing={2.25} sx={{pt:1}}><TextField required label="Hotelname" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><TextField label="Ort" value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/><TextField label="Region" value={form.region} onChange={e=>setForm({...form,region:e.target.value})}/></Stack></CrudDialog>; }

export function HotelsManagement() {
 const detailScrollRef=useRef<HTMLDivElement>(null);
 const permissions=usePermissions(); const [hotels,setHotels]=useState<Hotel[]>([]),[roomTypes,setRoomTypes]=useState<RoomType[]>([]),[bookings,setBookings]=useState<RoomBooking[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[selectedId,setSelectedId]=useState<string|null>(null),[search,setSearch]=useState(''),[region,setRegion]=useState('');
 const [hotelDialog,setHotelDialog]=useState<{open:boolean;hotel:Hotel|null}>({open:false,hotel:null}); const [contingentDialog,setContingentDialog]=useState<{open:boolean;mode:'create'|'edit';item:HotelRoomInventory|null}>({open:false,mode:'create',item:null}); const [deleting,setDeleting]=useState<HotelRoomInventory|null>(null);
 const load=async()=>{try{setLoading(true);const [h,r,b]=await Promise.all([api.getHotels(),api.getRoomTypes(),api.getRoomAssignments()]);setHotels(h);setRoomTypes(r);setBookings(b);setSelectedId(v=>v&&h.some(x=>x.id===v)?v:h[0]?.id||null);setError(null);}catch{setError('Hotels konnten nicht geladen werden.');}finally{setLoading(false);}}; useEffect(()=>{void load();},[]);
 const selected=hotels.find(h=>h.id===selectedId)||null, selectedStats=selected?stats(selected,bookings):null; const regions=useMemo(()=>[...new Set(hotels.map(h=>h.region).filter(Boolean) as string[])].sort(),[hotels]); const filtered=hotels.filter(h=>(!region||h.region===region)&&(!search.trim()||`${h.name} ${h.location} ${h.region}`.toLowerCase().includes(search.toLowerCase()))); const totals=hotels.reduce((a,h)=>{const s=stats(h,bookings);a.rooms+=s.freeRooms;a.beds+=s.freeBeds;return a;},{rooms:0,beds:0});
 const timelineRows:TimelineRowData[]=(selected?.roomInventories||[]).map(i=>({id:i.id,title:i.roomType.name,subtitle:`${i.roomCount} Zimmer · ${i.roomCount*i.roomType.maxPersons} Betten`,segments:[{id:i.id,start:i.availableFrom,end:i.availableUntil,color:'var(--ops-primary-emphasis)',tooltip:<span><b>{i.roomType.name}</b><br/>{date(i.availableFrom)} – {date(i.availableUntil)}<br/>{i.roomCount} Zimmer</span>}]}));
 useEffect(()=>{detailScrollRef.current?.scrollTo({top:0});},[selectedId]);
 if(loading)return <div className="flex h-64 items-center justify-center"><CircularProgress/></div>;
 return <PageLayout className="[--ops-background:#111d2e] [--ops-surface:#1a2a40] [--ops-surface-raised:#21334c] [--ops-surface-elevated:#2a3e59] [--ops-surface-overlay:#344b67] [--ops-border:#4b6380] [--ops-divider:#405773] [--ops-text-muted:#b7c4d4] xl:flex xl:h-full xl:min-h-0 xl:flex-col xl:gap-5 xl:space-y-0">
  <PageHeader eyebrow="Operations Center" title="Hotels & Zimmerkontingente" subtitle="Hotelstruktur, Verfügbarkeit und Kontingente im operativen Überblick." meta={<><StatusChip tone="success">{totals.rooms} freie Zimmer</StatusChip><StatusChip tone="primary">{totals.beds} freie Betten</StatusChip></>} actions={<OpsButton onClick={()=>setHotelDialog({open:true,hotel:null})} disabled={!permissions.canCreate} title={!permissions.canCreate?READ_ONLY_TOOLTIP:undefined}><Plus className="mr-2 inline h-4 w-4"/>Hotel hinzufügen</OpsButton>}/>
  {error&&<InfoPanel tone="error" title="Fehler">{error}</InfoPanel>}
  <div className="flex flex-col gap-5 xl:min-h-0 xl:flex-1 xl:flex-row">
   <ContentCard surface="raised" className="flex flex-col overflow-hidden xl:w-[22rem] xl:min-h-0 xl:shrink-0"><div className="shrink-0 border-b border-[var(--ops-divider)] p-4"><SectionHeader title={`Hotelliste (${filtered.length})`}/><label className="mt-4 flex items-center gap-2 rounded-lg border border-[var(--ops-border)] bg-[var(--ops-surface-elevated)] px-3 py-2"><Search className="h-4 w-4"/><input className="w-full bg-transparent text-sm text-[var(--ops-text)] outline-none" placeholder="Hotel oder Ort suchen" value={search} onChange={e=>setSearch(e.target.value)}/></label><select className="mt-3 w-full rounded-lg border border-[var(--ops-border)] bg-[var(--ops-surface-elevated)] px-3 py-2 text-sm" value={region} onChange={e=>setRegion(e.target.value)}><option value="">Alle Regionen</option>{regions.map(r=><option key={r}>{r}</option>)}</select></div><div className="space-y-2 p-3 xl:min-h-0 xl:flex-1 xl:overflow-y-auto">{filtered.map(h=>{const s=stats(h,bookings);return <button key={h.id} onClick={()=>setSelectedId(h.id)} className={clsx('w-full rounded-xl border p-3 text-left transition hover:bg-[var(--ops-surface-elevated)]',selectedId===h.id?'border-[var(--ops-primary)] bg-[var(--ops-surface-overlay)]':'border-[var(--ops-border)] bg-[var(--ops-surface)]')}><div className="flex justify-between gap-2"><div><b>{h.name}</b><div className="text-xs text-[var(--ops-text-muted)]">{h.location||'Kein Ort'} · {h.region||'Keine Region'}</div></div><StatusChip tone={s.tone}>{s.status}</StatusChip></div><div className="my-2 flex justify-between text-xs text-[var(--ops-text-muted)]"><span>{s.freeRooms} Zi. frei · {s.freeBeds} Betten frei</span><b>{s.occupancy.toFixed(0)}%</b></div><Bar value={s.occupancy} tone={s.tone}/></button>})}{!filtered.length&&<EmptyState title="Keine Hotels gefunden"/>}</div></ContentCard>
   <ContentCard surface="raised" className="overflow-hidden xl:min-h-0 xl:flex-1"><div ref={detailScrollRef} className="xl:h-full xl:overflow-y-auto">{selected&&selectedStats?<div><div className="border-b border-[var(--ops-divider)] p-5"><div className="flex items-start justify-between gap-4"><div><SectionHeader title="Hotelinformationen"/><h2 className="mt-3 text-2xl font-extrabold">{selected.name}</h2><p className="text-sm text-[var(--ops-text-muted)]">{selected.location||'Kein Ort'} · {selected.region||'Keine Region'} · {selectedStats.range}</p><div className="mt-3 flex gap-2">{(selected.roomInventories||[]).some(i=>i.hasHalfBoard)&&<StatusChip tone="info">HP</StatusChip>}{(selected.roomInventories||[]).some(i=>i.hasSR)&&<StatusChip tone="info">SR</StatusChip>}</div></div><OpsButton disabled={!permissions.canEdit} onClick={()=>setHotelDialog({open:true,hotel:selected})}><Pencil className="mr-2 inline h-4 w-4"/>Hotel bearbeiten</OpsButton></div></div>
    <div className="space-y-6 p-5"><SectionHeader title="Verfügbarkeit"/><div className="grid grid-cols-2 gap-3 lg:grid-cols-5"><Metric label="Freie Zimmer" value={selectedStats.freeRooms} icon={<DoorOpen size={15}/>}/><Metric label="Belegte Zimmer" value={selectedStats.occupiedRooms} icon={<Building2 size={15}/>}/><Metric label="Freie Betten" value={selectedStats.freeBeds} icon={<BedDouble size={15}/>}/><Metric label="Belegte Betten" value={selectedStats.occupiedBeds} icon={<Users size={15}/>}/><Metric label="Auslastung" value={`${selectedStats.occupancy.toFixed(0)}%`} icon={<Users size={15}/>}/></div>
    <SectionHeader title="Zimmerkategorien & Kontingente" actions={<OpsButton disabled={!permissions.canCreate} onClick={()=>setContingentDialog({open:true,mode:'create',item:null})}><Plus className="mr-2 inline h-4 w-4"/>Kontingent erstellen</OpsButton>}/><div className="grid gap-3 lg:grid-cols-2">{(selected.roomInventories||[]).map(i=>{const s=stats(selected,bookings,i);return <ContentCard key={i.id} interactive className="p-4"><div className="flex justify-between"><div><h3 className="text-lg font-extrabold">{i.roomType.name}</h3><p className="text-xs text-[var(--ops-text-muted)]">{s.range}</p></div><div className="flex gap-2"><button aria-label="Kontingent bearbeiten" onClick={()=>setContingentDialog({open:true,mode:'edit',item:i})}><Pencil size={17}/></button><button aria-label="Kontingent löschen" className="text-[var(--ops-error)]" onClick={()=>setDeleting(i)}><Trash2 size={17}/></button></div></div><div className="mt-3 grid grid-cols-3 gap-2 text-xs"><span>Zimmer gesamt<b className="block text-lg">{s.totalRooms}</b></span><span>Zimmer frei<b className="block text-lg">{s.freeRooms}</b></span><span>Zimmer belegt<b className="block text-lg">{s.occupiedRooms}</b></span><span>Betten gesamt<b className="block text-lg">{s.totalBeds}</b></span><span>Betten frei<b className="block text-lg">{s.freeBeds}</b></span><span>Auslastung<b className="block text-lg">{s.occupancy.toFixed(0)}%</b></span></div><div className="mt-3 flex gap-2">{i.hasHalfBoard&&<StatusChip tone="info">HP-Aufpreis</StatusChip>}{i.hasSR&&<StatusChip tone="info">SR-Aufpreis</StatusChip>}</div><div className="mt-3"><Bar value={s.occupancy} tone={s.tone}/></div></ContentCard>})}</div>{!(selected.roomInventories||[]).length&&<EmptyState title="Keine Zimmerkontingente" description="Erstellen Sie das erste Kontingent für dieses Hotel."/>}
    <SectionHeader title="Timeline" subtitle="Zimmerkontingente auf dem gesamten WM-Zeitraum · 04.03. bis 22.03.2027"/><OperationsTimeline startDate="2027-03-04" endDate="2027-03-22" rows={timelineRows} emptyMessage="Für dieses Hotel sind noch keine Zeiträume angelegt." legend={[{label:'Verfügbarkeit des Zimmerkontingents',color:'var(--ops-primary-emphasis)'}]}/></div></div>:<div className="p-12"><EmptyState title="Kein Hotel ausgewählt" description="Wählen Sie links ein Hotel aus."/></div>}</div></ContentCard>
  </div>
  <HotelDialog open={hotelDialog.open} hotel={hotelDialog.hotel} onClose={()=>setHotelDialog({open:false,hotel:null})} onSave={async v=>{hotelDialog.hotel?await api.updateHotel(hotelDialog.hotel.id,v):await api.createHotel(v);await load();}}/>
  <HotelContingentDialog open={contingentDialog.open} mode={contingentDialog.mode} hotel={selected} contingent={contingentDialog.item} roomTypes={roomTypes} onClose={()=>setContingentDialog({open:false,mode:'create',item:null})} onSubmit={async(v:HotelContingentValues)=>{if(!selected)return;const payload={...v,roomCount:Number(v.roomCount)};contingentDialog.mode==='edit'&&contingentDialog.item?await api.updateHotelInventory(selected.id,contingentDialog.item.id,payload):await api.addHotelInventory(selected.id,payload);await load();}}/>
  <Dialog open={Boolean(deleting)} onClose={()=>setDeleting(null)}><DialogTitle>Kontingent löschen?</DialogTitle><DialogContent>Das Kontingent <b>{deleting?.roomType.name}</b> wird dauerhaft entfernt.</DialogContent><DialogActions><Button onClick={()=>setDeleting(null)}>Abbrechen</Button><Button color="error" variant="contained" onClick={async()=>{if(selected&&deleting){await api.deleteHotelInventory(selected.id,deleting.id);setDeleting(null);await load();}}}>Löschen</Button></DialogActions></Dialog>
 </PageLayout>;
}
