import { useEffect, useMemo, useState, type ReactNode } from 'react';
import { useNavigate } from 'react-router';
import { Bar, BarChart, CartesianGrid, Cell, ComposedChart, Legend, Line, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { AlertTriangle, ArrowRight, Building2, CalendarRange, ChartNoAxesCombined, CircleUserRound, Loader2, ListChecks } from 'lucide-react';
import { clsx } from 'clsx';
import { api } from '../services/api';
import type { Athlete, Event, Hotel, HotelRoomInventory, RoomBooking } from '../types';
import { ContentCard, DataPanel, EmptyState, ErrorState, MetricCard, PageHeader, PageLayout, SectionHeader, StatusChip } from '../design-system';

type ViewKey = 'capacity' | 'hotels' | 'assignments' | 'events' | 'singleRooms' | 'conflicts';
type AnalyticsData = { hotels: Hotel[]; events: Event[]; athletes: Athlete[]; bookings: RoomBooking[] };
type Tone = 'neutral' | 'success' | 'warning' | 'error' | 'info' | 'primary';

const isSingle = (room: { name: string; maxPersons: number }) => room.maxPersons === 1 || /(^|\W)EZ(\W|$)/i.test(room.name);
const dayKey = (value?: string | null) => value?.slice(0, 10) || '';
const formatDay = (value: string) => new Date(`${value}T00:00:00Z`).toLocaleDateString('de-DE', { day: '2-digit', month: '2-digit', timeZone: 'UTC' });
const range = (from: string, until: string) => {
  const result: string[] = [];
  for (let date = new Date(`${from}T00:00:00Z`), end = new Date(`${until}T00:00:00Z`); date <= end; date.setUTCDate(date.getUTCDate() + 1)) result.push(date.toISOString().slice(0, 10));
  return result;
};
const inventoryRooms = (items: HotelRoomInventory[] = []) => items.reduce((sum, item) => sum + item.roomCount, 0);
const inventoryBeds = (items: HotelRoomInventory[] = []) => items.reduce((sum, item) => sum + item.roomCount * item.roomType.maxPersons, 0);
const isAssigned = (athlete: Athlete) => Boolean(athlete.assignment?.hasAssignment || athlete.assignments?.some(item => item.hasAssignment));
const eventForAthlete = (athlete: Athlete, events: Event[]) => events.find(event => athlete.disciplines?.includes(event.discipline) || athlete.discipline === event.discipline);

const NAV: Array<{ key: ViewKey; label: string; question: string; icon: typeof Building2 }> = [
  { key: 'capacity', label: 'Bedarf & Kontingent', question: 'Haben wir genügend Zimmer?', icon: ChartNoAxesCombined },
  { key: 'hotels', label: 'Hotelauslastung', question: 'Welche Hotels laufen voll?', icon: Building2 },
  { key: 'assignments', label: 'Zuweisungsfortschritt', question: 'Wie weit ist die Belegung?', icon: ListChecks },
  { key: 'events', label: 'Eventbedarf', question: 'Welche Events treiben den Bedarf?', icon: CalendarRange },
  { key: 'singleRooms', label: 'Einzelzimmer', question: 'Welche Entscheidungen sind offen?', icon: CircleUserRound },
  { key: 'conflicts', label: 'Operative Konflikte', question: 'Wo müssen wir jetzt handeln?', icon: AlertTriangle },
];

function ClickMetric({ onClick, ...props }: Parameters<typeof MetricCard>[0] & { onClick: () => void }) {
  return <button type="button" onClick={onClick} className="min-w-0 text-left transition-transform hover:-translate-y-0.5 focus-visible:rounded-xl focus-visible:outline-none focus-visible:shadow-[var(--ops-focus-ring)]"><MetricCard {...props} /></button>;
}

function Kpis({ children }: { children: ReactNode }) { return <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{children}</div>; }
function ViewShell({ title, subtitle, children }: { title: string; subtitle: string; children: ReactNode }) {
  return <div className="min-w-0 space-y-4"><ContentCard surface="raised" className="p-5"><SectionHeader title="Operative Frage" /><h2 className="mt-2 text-2xl font-extrabold">{title}</h2><p className="mt-1 text-sm text-[var(--ops-text-muted)]">{subtitle}</p></ContentCard>{children}</div>;
}
function ActionCell() { return <ArrowRight size={16} className="text-[var(--ops-primary)]" />; }
function ChartTip() { return <Tooltip contentStyle={{ background: 'var(--ops-surface-elevated)', border: '1px solid var(--ops-border)', borderRadius: 8 }} />; }
const tableClass = 'w-full min-w-[42rem] text-sm';
const rowClass = 'cursor-pointer border-t border-[var(--ops-divider)] hover:bg-[var(--ops-surface-elevated)]';
const headClass = 'text-left text-[11px] uppercase tracking-wider text-[var(--ops-text-subtle)]';

function CapacityView({ data }: { data: AnalyticsData }) {
  const navigate = useNavigate();
  const dates = [...data.events.flatMap(event => [dayKey(event.startDate), dayKey(event.endDate)]), ...data.hotels.flatMap(hotel => (hotel.roomInventories || []).flatMap(item => [dayKey(item.availableFrom), dayKey(item.availableUntil)]))].filter(Boolean).sort();
  const days = dates.length ? range(dates[0], dates.at(-1)!) : [];
  const timeline = days.map(date => {
    const inventory = data.hotels.flatMap(h => h.roomInventories || []).filter(item => dayKey(item.availableFrom) <= date && dayKey(item.availableUntil) >= date);
    const events = data.events.filter(event => dayKey(event.startDate) <= date && dayKey(event.endDate) >= date);
    const demands = events.flatMap(event => event.roomDemands || []);
    const dzSupply = inventory.filter(item => !isSingle(item.roomType)).reduce((sum, item) => sum + item.roomCount, 0);
    const ezSupply = inventory.filter(item => isSingle(item.roomType)).reduce((sum, item) => sum + item.roomCount, 0);
    const dzDemand = demands.filter(item => !isSingle(item.roomType)).reduce((sum, item) => sum + item.roomCount, 0);
    const ezDemand = demands.filter(item => isSingle(item.roomType)).reduce((sum, item) => sum + item.roomCount, 0);
    return { date, label: formatDay(date), dzSupply, ezSupply, dzDemand, ezDemand, dzReserve: dzSupply - dzDemand, ezReserve: ezSupply - ezDemand };
  });
  const minDz = Math.min(0, ...timeline.map(day => day.dzReserve));
  const minEz = Math.min(0, ...timeline.map(day => day.ezReserve));
  const critical = timeline.filter(day => day.dzReserve < 0 || day.ezReserve < 0);
  return <ViewShell title="Haben wir genügend Zimmer?" subtitle="Bedarf der laufenden Events gegen das tagesgenaue DZ- und EZ-Kontingent.">
    <Kpis><ClickMetric onClick={() => navigate('/hotels?roomType=DZ')} label="DZ Reserve" value={minDz} helper="niedrigster Tageswert" trend={minDz < 0 ? 'Engpass' : 'gedeckt'} tone={minDz < 0 ? 'error' : 'success'} /><ClickMetric onClick={() => navigate('/hotels?roomType=EZ')} label="EZ Reserve" value={minEz} helper="niedrigster Tageswert" trend={minEz < 0 ? 'Engpass' : 'gedeckt'} tone={minEz < 0 ? 'error' : 'success'} /><ClickMetric onClick={() => navigate('/events')} label="Kritische Zeiträume" value={critical.length} helper="Tage mit Unterdeckung" trend={critical.length ? 'Handlungsbedarf' : 'stabil'} tone={critical.length ? 'error' : 'success'} /><ClickMetric onClick={() => navigate('/assignments')} label="Spitzentag Bedarf" value={Math.max(0, ...timeline.map(day => day.dzDemand + day.ezDemand))} helper="Zimmer gleichzeitig" trend="Assignments" tone="info" /></Kpis>
    <DataPanel title="Kontingent vs. Bedarf" actions={<StatusChip tone={critical.length ? 'error' : 'success'}>{critical.length ? `${critical.length} kritische Tage` : 'Bedarf gedeckt'}</StatusChip>}><button type="button" onClick={() => navigate('/hotels')} className="h-80 w-full p-4 text-left" aria-label="Hotelkontingente öffnen"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={timeline}><CartesianGrid stroke="var(--ops-divider)" vertical={false}/><XAxis dataKey="label" stroke="var(--ops-text-muted)" fontSize={11}/><YAxis stroke="var(--ops-text-muted)"/><ChartTip/><Legend/><Line type="monotone" dataKey="dzSupply" name="DZ Kontingent" stroke="var(--ops-primary)" strokeWidth={3} dot={false}/><Line type="monotone" dataKey="dzDemand" name="DZ Bedarf" stroke="var(--ops-error)" strokeWidth={2} dot={false}/><Line type="monotone" dataKey="ezSupply" name="EZ Kontingent" stroke="var(--ops-info)" strokeWidth={3} dot={false}/><Line type="monotone" dataKey="ezDemand" name="EZ Bedarf" stroke="var(--ops-warning)" strokeWidth={2} dot={false}/></ComposedChart></ResponsiveContainer></button></DataPanel>
    <DataPanel title="Tagesreserven"><div className="overflow-x-auto"><table className={tableClass}><thead className={headClass}><tr><th className="p-3">Zeitraum</th><th>DZ Bedarf / Kontingent</th><th>EZ Bedarf / Kontingent</th><th>Reserve</th><th>Ampel</th><th/></tr></thead><tbody>{timeline.map(day => { const reserve = day.dzReserve + day.ezReserve; const bad = day.dzReserve < 0 || day.ezReserve < 0; return <tr key={day.date} onClick={() => navigate(`/hotels?date=${day.date}`)} className={clsx(rowClass, bad && 'bg-[var(--ops-tone-error-surface)]')}><td className="p-3 font-bold">{day.label}</td><td>{day.dzDemand} / {day.dzSupply}</td><td>{day.ezDemand} / {day.ezSupply}</td><td className="font-mono font-bold">{reserve > 0 ? '+' : ''}{reserve}</td><td><StatusChip tone={bad ? 'error' : reserve < 10 ? 'warning' : 'success'}>{bad ? 'kritisch' : reserve < 10 ? 'knapp' : 'gedeckt'}</StatusChip></td><td><ActionCell/></td></tr>; })}</tbody></table>{!timeline.length && <EmptyState title="Keine Zeiträume vorhanden" />}</div></DataPanel>
  </ViewShell>;
}

function HotelsView({ data }: { data: AnalyticsData }) {
  const navigate = useNavigate();
  const rows = data.hotels.map(hotel => { const rooms = inventoryRooms(hotel.roomInventories); const beds = inventoryBeds(hotel.roomInventories); const bookings = data.bookings.filter(item => item.hotel.id === hotel.id); const occupiedRooms = bookings.length; const occupiedBeds = bookings.reduce((sum, item) => sum + item.occupants.length, 0); return { id: hotel.id, name: hotel.name, rooms, beds, occupiedRooms, freeRooms: Math.max(0, rooms - occupiedRooms), freeBeds: Math.max(0, beds - occupiedBeds), utilization: rooms ? Math.round(occupiedRooms / rooms * 100) : 0 }; }).sort((a, b) => b.utilization - a.utilization);
  const top = rows[0];
  return <ViewShell title="Welche Hotels laufen voll?" subtitle="Belegte Buchungseinheiten im Verhältnis zum hinterlegten Zimmerkontingent."><Kpis><ClickMetric onClick={() => navigate('/hotels?availability=free')} label="Freie Zimmer" value={rows.reduce((s, r) => s + r.freeRooms, 0)} helper="über alle Hotels" trend="Kapazität" tone="info"/><ClickMetric onClick={() => navigate('/hotels?availability=beds')} label="Freie Betten" value={rows.reduce((s, r) => s + r.freeBeds, 0)} helper="rechnerisch verfügbar" trend="Kapazität" tone="info"/><ClickMetric onClick={() => top && navigate(`/hotels?hotelId=${top.id}`)} label="Höchste Auslastung" value={`${top?.utilization || 0}%`} helper={top?.name || 'Kein Hotel'} trend={(top?.utilization || 0) >= 90 ? 'kritisch' : 'beobachten'} tone={(top?.utilization || 0) >= 90 ? 'error' : 'warning'}/></Kpis><DataPanel title="Hotelauslastung – Ranking"><button type="button" onClick={() => top && navigate(`/hotels?hotelId=${top.id}`)} className="h-80 w-full p-4"><ResponsiveContainer width="100%" height="100%"><BarChart data={rows.slice(0, 12)} layout="vertical" margin={{ left: 30 }}><CartesianGrid stroke="var(--ops-divider)" horizontal={false}/><XAxis type="number" domain={[0, 100]} unit="%" stroke="var(--ops-text-muted)"/><YAxis type="category" dataKey="name" width={150} tick={{ fill: 'var(--ops-text-muted)', fontSize: 11 }}/><ChartTip/><Bar dataKey="utilization" name="Auslastung %" radius={[0, 5, 5, 0]}>{rows.slice(0, 12).map(row => <Cell key={row.id} fill={row.utilization >= 90 ? 'var(--ops-error)' : row.utilization >= 75 ? 'var(--ops-warning)' : 'var(--ops-primary)'}/>)}</Bar></BarChart></ResponsiveContainer></button></DataPanel><DataPanel title="Kapazität je Hotel"><div className="overflow-x-auto"><table className={tableClass}><thead className={headClass}><tr><th className="p-3">Hotel</th><th>Auslastung</th><th>Zimmer</th><th>Freie Zimmer</th><th>Freie Betten</th><th/></tr></thead><tbody>{rows.map(row => <tr key={row.id} onClick={() => navigate(`/hotels?hotelId=${row.id}`)} className={rowClass}><td className="p-3 font-bold">{row.name}</td><td><StatusChip tone={row.utilization >= 90 ? 'error' : row.utilization >= 75 ? 'warning' : 'success'}>{row.utilization}%</StatusChip></td><td>{row.occupiedRooms} / {row.rooms}</td><td>{row.freeRooms}</td><td>{row.freeBeds}</td><td><ActionCell/></td></tr>)}</tbody></table></div></DataPanel></ViewShell>;
}

function AssignmentsView({ data }: { data: AnalyticsData }) {
  const navigate = useNavigate(); const assigned = data.athletes.filter(isAssigned).length; const open = data.athletes.length - assigned; const percent = data.athletes.length ? Math.round(assigned / data.athletes.length * 100) : 0;
  const rows = data.events.map(event => { const athletes = data.athletes.filter(a => eventForAthlete(a, [event])); const done = athletes.filter(isAssigned).length; return { id: event.id, name: event.discipline, demand: event.personDemand || athletes.length, assigned: done, open: Math.max(0, (event.personDemand || athletes.length) - done) }; }).sort((a, b) => b.open - a.open);
  return <ViewShell title="Wie weit ist die Belegung?" subtitle="Zugewiesene und offene Personen – aufgeschlüsselt nach Event."><Kpis><ClickMetric onClick={() => navigate('/athletes')} label="Personen" value={data.athletes.length} helper="im WM-Zeitraum" trend="gesamt"/><ClickMetric onClick={() => navigate('/assignments?status=assigned')} label="Zugewiesen" value={assigned} helper="mit Zimmer" trend={`${percent}%`} tone="success"/><ClickMetric onClick={() => navigate('/assignments?status=open')} label="Offen" value={open} helper="ohne Zimmer" trend={open ? 'bearbeiten' : 'erledigt'} tone={open ? 'error' : 'success'}/><ClickMetric onClick={() => navigate('/assignments')} label="Fortschritt" value={`${percent}%`} helper="Zuweisungsquote" trend={percent >= 90 ? 'im Plan' : 'offen'} tone={percent >= 90 ? 'success' : 'warning'}/></Kpis><DataPanel title="Zuweisung pro Event"><button onClick={() => navigate('/assignments')} className="h-80 w-full p-4"><ResponsiveContainer width="100%" height="100%"><BarChart data={rows}><CartesianGrid stroke="var(--ops-divider)" vertical={false}/><XAxis dataKey="name" stroke="var(--ops-text-muted)" fontSize={11}/><YAxis stroke="var(--ops-text-muted)"/><ChartTip/><Legend/><Bar stackId="a" dataKey="assigned" name="Zugewiesen" fill="var(--ops-success)"/><Bar stackId="a" dataKey="open" name="Offen" fill="var(--ops-error)" radius={[5, 5, 0, 0]}/></BarChart></ResponsiveContainer></button></DataPanel><DataPanel title="Fortschritt nach Event"><div className="overflow-x-auto"><table className={tableClass}><thead className={headClass}><tr><th className="p-3">Event</th><th>Bedarf</th><th>Zugewiesen</th><th>Offen</th><th>Status</th><th/></tr></thead><tbody>{rows.map(row => <tr key={row.id} onClick={() => navigate(`/assignments?eventId=${row.id}`)} className={rowClass}><td className="p-3 font-bold">{row.name}</td><td>{row.demand}</td><td>{row.assigned}</td><td className="font-bold">{row.open}</td><td><StatusChip tone={row.open ? 'warning' : 'success'}>{row.open ? 'in Arbeit' : 'vollständig'}</StatusChip></td><td><ActionCell/></td></tr>)}</tbody></table></div></DataPanel></ViewShell>;
}

function EventsView({ data }: { data: AnalyticsData }) {
  const navigate = useNavigate(); const rows = data.events.map(event => { const dz = (event.roomDemands || []).filter(d => !isSingle(d.roomType)).reduce((s, d) => s + d.roomCount, 0); const ez = (event.roomDemands || []).filter(d => isSingle(d.roomType)).reduce((s, d) => s + d.roomCount, 0); return { id: event.id, name: event.discipline, dz, ez, rooms: dz + ez, beds: (event.roomDemands || []).reduce((s, d) => s + d.roomCount * d.roomType.maxPersons, 0), persons: event.personDemand, period: `${formatDay(dayKey(event.startDate))}–${formatDay(dayKey(event.endDate))}` }; }).sort((a, b) => b.beds - a.beds); const biggest = rows[0];
  return <ViewShell title="Welche Events erzeugen den größten Bedarf?" subtitle="Zimmer- und Bettenbedarf pro Event und Veranstaltungszeitraum."><Kpis><ClickMetric onClick={() => biggest && navigate(`/events?eventId=${biggest.id}`)} label="Größtes Event" value={biggest?.name || '—'} helper={biggest?.period || 'kein Zeitraum'} trend="öffnen" tone="primary"/><ClickMetric onClick={() => biggest && navigate(`/events?eventId=${biggest.id}`)} label="Betten" value={biggest?.beds || 0} helper="Spitzenbedarf Event" trend="Bedarf" tone="info"/><ClickMetric onClick={() => biggest && navigate(`/events?eventId=${biggest.id}`)} label="Zimmer" value={biggest?.rooms || 0} helper="Spitzenbedarf Event" trend="Bedarf" tone="info"/></Kpis><DataPanel title="Eventbedarf nach Zeitraum"><button onClick={() => navigate('/events')} className="h-80 w-full p-4"><ResponsiveContainer width="100%" height="100%"><BarChart data={rows} layout="vertical" margin={{ left: 30 }}><CartesianGrid stroke="var(--ops-divider)" horizontal={false}/><XAxis type="number" stroke="var(--ops-text-muted)"/><YAxis type="category" dataKey="name" width={150} tick={{ fill: 'var(--ops-text-muted)', fontSize: 11 }}/><ChartTip/><Legend/><Bar dataKey="dz" name="DZ" stackId="a" fill="var(--ops-primary)"/><Bar dataKey="ez" name="EZ" stackId="a" fill="var(--ops-warning)" radius={[0, 5, 5, 0]}/></BarChart></ResponsiveContainer></button></DataPanel><DataPanel title="Bedarf je Event"><div className="overflow-x-auto"><table className={tableClass}><thead className={headClass}><tr><th className="p-3">Event</th><th>Zeitraum</th><th>DZ</th><th>EZ</th><th>Betten</th><th>Personen</th><th/></tr></thead><tbody>{rows.map(row => <tr key={row.id} onClick={() => navigate(`/events?eventId=${row.id}`)} className={rowClass}><td className="p-3 font-bold">{row.name}</td><td>{row.period}</td><td>{row.dz}</td><td>{row.ez}</td><td>{row.beds}</td><td>{row.persons}</td><td><ActionCell/></td></tr>)}</tbody></table></div></DataPanel></ViewShell>;
}

function SingleRoomsView({ data }: { data: AnalyticsData }) {
  const navigate = useNavigate(); const defs: Array<{ status: Athlete['single_room_status']; label: string; tone: Tone }> = [{ status: 'PENDING_APPROVAL', label: 'Offen', tone: 'warning' }, { status: 'IN_QUOTA', label: 'Innerhalb Quote', tone: 'success' }, { status: 'APPROVED_EXTRA', label: 'Genehmigt', tone: 'info' }, { status: 'NONE', label: 'Abgelehnt / kein EZ', tone: 'neutral' }]; const chart = defs.map(def => ({ ...def, value: data.athletes.filter(a => a.single_room_status === def.status).length })); const people = data.athletes.filter(a => a.single_room_status !== 'NONE').sort((a, b) => (a.single_room_status === 'PENDING_APPROVAL' ? -1 : b.single_room_status === 'PENDING_APPROVAL' ? 1 : a.lastname.localeCompare(b.lastname)));
  return <ViewShell title="Wo stehen die Einzelzimmerentscheidungen?" subtitle="Status, Quote und offene Entscheidungen mit direktem Sprung zur Person."><Kpis>{chart.map(item => <ClickMetric key={item.status} onClick={() => navigate(`/athletes?singleRoomStatus=${item.status}`)} label={item.label} value={item.value} helper="Personen" trend="anzeigen" tone={item.tone}/>)}</Kpis><DataPanel title="Verteilung Einzelzimmerstatus"><button onClick={() => navigate('/athletes?singleRoom=true')} className="h-72 w-full p-4"><ResponsiveContainer width="100%" height="100%"><BarChart data={chart}><CartesianGrid stroke="var(--ops-divider)" vertical={false}/><XAxis dataKey="label" stroke="var(--ops-text-muted)"/><YAxis stroke="var(--ops-text-muted)" allowDecimals={false}/><ChartTip/><Bar dataKey="value" name="Personen" radius={[5,5,0,0]}>{chart.map(item => <Cell key={item.status} fill={item.status === 'PENDING_APPROVAL' ? 'var(--ops-warning)' : item.status === 'IN_QUOTA' ? 'var(--ops-success)' : 'var(--ops-primary)'}/>)}</Bar></BarChart></ResponsiveContainer></button></DataPanel><DataPanel title="Personen"><div className="overflow-x-auto"><table className={tableClass}><thead className={headClass}><tr><th className="p-3">Person</th><th>Nation</th><th>Disziplin</th><th>Status</th><th/></tr></thead><tbody>{people.map(person => { const def = defs.find(d => d.status === person.single_room_status)!; return <tr key={person.id} onClick={() => navigate(`/athletes?athleteId=${person.id}`)} className={rowClass}><td className="p-3 font-bold">{person.firstname} {person.lastname}</td><td>{person.nationCode}</td><td>{person.discipline || person.disciplines?.join(', ') || '—'}</td><td><StatusChip tone={def.tone}>{def.label}</StatusChip></td><td><ActionCell/></td></tr>})}</tbody></table></div></DataPanel></ViewShell>;
}

function ConflictsView({ data }: { data: AnalyticsData }) {
  const navigate = useNavigate(); const conflicts = data.athletes.flatMap(athlete => { const base = { athlete, id: athlete.id }; if (!isAssigned(athlete)) return [{ ...base, priority: 1, title: 'Athlet ohne Zimmer', detail: 'Keine gültige Zimmerzuweisung vorhanden', route: `/assignments?athleteId=${athlete.id}` }]; if (athlete.hasPendingRoomlistReview) return [{ ...base, priority: 2, title: 'Zuweisung nach Import prüfen', detail: athlete.roomlistChangeSummary || 'Zimmerrelevante Daten wurden geändert', route: `/athletes?athleteId=${athlete.id}` }]; if (athlete.single_room_status === 'PENDING_APPROVAL') return [{ ...base, priority: 3, title: 'EZ-Entscheidung offen', detail: 'Einzelzimmerbedarf ist noch nicht entschieden', route: `/athletes?athleteId=${athlete.id}` }]; return []; }).sort((a, b) => a.priority - b.priority);
  return <ViewShell title="Wo besteht akuter Handlungsbedarf?" subtitle="Keine Statistik: eine priorisierte Arbeitsliste mit direktem Einstieg in die Lösung."><Kpis><ClickMetric onClick={() => navigate('/assignments?status=open')} label="Kritisch" value={conflicts.filter(c => c.priority === 1).length} helper="Zimmer fehlt" trend="sofort" tone="error"/><ClickMetric onClick={() => navigate('/athletes?review=pending')} label="Zu prüfen" value={conflicts.filter(c => c.priority === 2).length} helper="Importkonflikte" trend="heute" tone="warning"/><ClickMetric onClick={() => navigate('/athletes?singleRoomStatus=PENDING_APPROVAL')} label="Entscheidungen" value={conflicts.filter(c => c.priority === 3).length} helper="EZ offen" trend="bearbeiten" tone="warning"/><ClickMetric onClick={() => navigate('/assignments')} label="Gesamt" value={conflicts.length} helper="offene Aufgaben" trend={conflicts.length ? 'Handlungsbedarf' : 'alles stabil'} tone={conflicts.length ? 'error' : 'success'}/></Kpis><DataPanel title="Priorisierte Aufgaben" actions={<StatusChip tone={conflicts.length ? 'error' : 'success'}>{conflicts.length ? `${conflicts.length} offen` : 'Keine Konflikte'}</StatusChip>}><div className="divide-y divide-[var(--ops-divider)]">{conflicts.map(item => <button key={`${item.id}-${item.priority}`} onClick={() => navigate(item.route)} className="group flex w-full items-center gap-4 p-4 text-left hover:bg-[var(--ops-surface-elevated)]"><span className={clsx('flex h-9 w-9 shrink-0 items-center justify-center rounded-full font-mono font-bold', item.priority === 1 ? 'bg-[var(--ops-tone-error-surface)] text-[var(--ops-error)]' : 'bg-[var(--ops-tone-warning-surface)] text-[var(--ops-warning)]')}>{item.priority}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><StatusChip tone={item.priority === 1 ? 'error' : 'warning'}>{item.title}</StatusChip><b>{item.athlete.firstname} {item.athlete.lastname}</b></div><p className="mt-1 text-xs text-[var(--ops-text-muted)]">{item.athlete.nationCode} · {item.athlete.discipline || item.athlete.disciplines?.join(', ') || 'Ohne Disziplin'} · {item.detail}</p></div><ActionCell/></button>)}{!conflicts.length && <div className="p-4"><EmptyState title="Keine operativen Konflikte" description="Aktuell besteht kein Handlungsbedarf." /></div>}</div></DataPanel></ViewShell>;
}

function Navigation({ active, data, onSelect }: { active: ViewKey; data: AnalyticsData; onSelect: (key: ViewKey) => void }) {
  const urgent = data.athletes.filter(a => !isAssigned(a) || a.hasPendingRoomlistReview || a.single_room_status === 'PENDING_APPROVAL').length;
  return <ContentCard surface="raised" className="overflow-hidden xl:w-[21rem] xl:shrink-0"><div className="border-b border-[var(--ops-divider)] p-4"><SectionHeader title="Entscheidungsbereiche" subtitle="Frage auswählen und direkt handeln" /></div><div className="grid gap-2 p-3 sm:grid-cols-2 xl:grid-cols-1" role="tablist">{NAV.map(item => { const Icon = item.icon; return <button key={item.key} type="button" role="tab" aria-selected={active === item.key} onClick={() => onSelect(item.key)} className={clsx('group flex items-center gap-3 rounded-xl border p-3 text-left transition-colors', active === item.key ? 'border-[var(--ops-primary)] bg-[var(--ops-surface-overlay)] shadow-[0_0_0_1px_var(--ops-primary)]' : 'border-[var(--ops-border)] bg-[var(--ops-surface)] hover:bg-[var(--ops-surface-elevated)]')}><span className="rounded-lg bg-[var(--ops-surface-elevated)] p-2 text-[var(--ops-primary)]"><Icon size={19}/></span><span className="min-w-0 flex-1"><b className="block text-sm">{item.label}</b><small className="block truncate text-[var(--ops-text-muted)]">{item.question}</small></span>{item.key === 'conflicts' && urgent > 0 ? <StatusChip tone="error">{urgent}</StatusChip> : <ArrowRight size={16} className="text-[var(--ops-primary)]"/>}</button>; })}</div></ContentCard>;
}

export function RoomAnalytics() {
  const [active, setActive] = useState<ViewKey>('capacity'); const [data, setData] = useState<AnalyticsData>({ hotels: [], events: [], athletes: [], bookings: [] }); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  useEffect(() => { void Promise.all([api.getHotels(), api.getEvents(), api.getAthletes(), api.getRoomAssignments()]).then(([hotels, events, athletes, bookings]) => { setData({ hotels, events, athletes, bookings }); setError(null); }).catch(() => setError('Analytics-Daten konnten nicht geladen werden.')).finally(() => setLoading(false)); }, []);
  const updated = useMemo(() => new Intl.DateTimeFormat('de-DE', { hour: '2-digit', minute: '2-digit' }).format(new Date()), [data]);
  if (loading) return <div className="flex h-64 items-center justify-center"><Loader2 className="h-8 w-8 animate-spin text-blue-600"/></div>;
  return <PageLayout className="[--ops-background:#111d2e] [--ops-surface:#1a2a40] [--ops-surface-raised:#21334c] [--ops-surface-elevated:#2a3e59] [--ops-surface-overlay:#344b67] [--ops-border:#4b6380] [--ops-divider:#405773] [--ops-text-muted:#b7c4d4]"><PageHeader eyebrow="Operations Center · Unterkunftsplanung" title="Operations Cockpit" subtitle="Engpässe erkennen, Ursachen verstehen und ohne Umweg in den richtigen Arbeitsbereich springen." meta={<><StatusChip tone="success">Live-Daten</StatusChip><StatusChip tone="neutral"><CalendarRange className="mr-1 h-3 w-3"/>Aktualisiert {updated} Uhr</StatusChip></>}/>{error && <ErrorState title="Daten nicht verfügbar" description={error}/>}<div className="flex flex-col gap-4 xl:flex-row"><Navigation active={active} data={data} onSelect={setActive}/><main className="min-w-0 flex-1" role="tabpanel">{active === 'capacity' && <CapacityView data={data}/>} {active === 'hotels' && <HotelsView data={data}/>} {active === 'assignments' && <AssignmentsView data={data}/>} {active === 'events' && <EventsView data={data}/>} {active === 'singleRooms' && <SingleRoomsView data={data}/>} {active === 'conflicts' && <ConflictsView data={data}/>}</main></div></PageLayout>;
}
