import { useEffect, useMemo, useState, type ReactNode } from 'react';
import { useNavigate } from 'react-router';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { AlertTriangle, ArrowRight, BedDouble, Building2, CalendarRange, DoorOpen, Flag, Loader2, Medal, UserRoundCheck } from 'lucide-react';
import { clsx } from 'clsx';
import { api } from '../services/api';
import type { Athlete, Event, Hotel, RoomBooking } from '../types';
import { ContentCard, EmptyState, ErrorState, PageHeader, PageLayout, SectionHeader, StatusChip } from '../design-system';

type AnalyticsKey = 'hotels' | 'rooms' | 'beds' | 'nations' | 'disciplines' | 'singleRooms' | 'conflicts';
type AnalyticsData = { hotels: Hotel[]; events: Event[]; athletes: Athlete[]; bookings: RoomBooking[] };
type KpiDefinition = { key: AnalyticsKey; label: string; helper: string; icon: typeof Building2; tone: string; value: (data: AnalyticsData) => number };

const roomCount = (hotels: Hotel[]) => hotels.reduce((sum, hotel) => sum + (hotel.roomInventories || []).reduce((total, item) => total + item.roomCount, 0), 0);
const bedCount = (hotels: Hotel[]) => hotels.reduce((sum, hotel) => sum + (hotel.roomInventories || []).reduce((total, item) => total + item.roomCount * item.roomType.maxPersons, 0), 0);
const pendingSingleRooms = (athletes: Athlete[]) => athletes.filter(athlete => athlete.single_room_status === 'PENDING_APPROVAL').length;
const conflictCount = (data: AnalyticsData) => data.athletes.filter(athlete => !athlete.assignment?.hasAssignment || athlete.hasPendingRoomlistReview || athlete.single_room_status === 'PENDING_APPROVAL').length;

const KPI_DEFINITIONS: KpiDefinition[] = [
  { key: 'hotels', label: 'Hotels', helper: 'Kapazität nach Standort', icon: Building2, tone: 'text-sky-300', value: data => data.hotels.length },
  { key: 'rooms', label: 'Zimmer', helper: 'Kontingent im Zeitraum', icon: DoorOpen, tone: 'text-blue-300', value: data => roomCount(data.hotels) },
  { key: 'beds', label: 'Betten', helper: 'Verfügbare Kapazität', icon: BedDouble, tone: 'text-indigo-300', value: data => bedCount(data.hotels) },
  { key: 'nations', label: 'Nationen', helper: 'Teilnehmende Teams', icon: Flag, tone: 'text-cyan-300', value: data => new Set(data.athletes.map(a => a.nationCode).filter(Boolean)).size },
  { key: 'disciplines', label: 'Disziplinen', helper: 'Eventportfolio', icon: Medal, tone: 'text-violet-300', value: data => new Set([...data.events.map(e => e.discipline), ...data.athletes.flatMap(a => a.disciplines || [a.discipline || ''])].filter(Boolean)).size },
  { key: 'singleRooms', label: 'Einzelzimmer', helper: 'Offene Entscheidungen', icon: UserRoundCheck, tone: 'text-amber-300', value: data => pendingSingleRooms(data.athletes) },
  { key: 'conflicts', label: 'Konflikte', helper: 'Operativer Handlungsbedarf', icon: AlertTriangle, tone: 'text-rose-300', value: conflictCount },
];

function KpiNavigation({ active, data, onSelect }: { active: AnalyticsKey; data: AnalyticsData; onSelect: (key: AnalyticsKey) => void }) {
  return <ContentCard surface="raised" className="overflow-hidden xl:w-[22rem] xl:shrink-0">
    <div className="border-b border-[var(--ops-divider)] p-4"><SectionHeader title="Kennzahlen" subtitle="KPI auswählen, um Ursachen zu analysieren" /></div>
    <div className="grid grid-cols-2 gap-2 p-3 sm:grid-cols-3 xl:grid-cols-1" role="tablist" aria-label="Analytics-Kennzahlen">
      {KPI_DEFINITIONS.map(({ key, label, helper, icon: Icon, tone, value }) => <button key={key} type="button" role="tab" aria-selected={active === key} onClick={() => onSelect(key)} className={clsx('group rounded-xl border p-3 text-left transition-all duration-150 hover:-translate-y-0.5 hover:border-[var(--ops-border-strong)] hover:bg-[var(--ops-surface-elevated)]', active === key ? 'border-[var(--ops-primary)] bg-[var(--ops-surface-overlay)] shadow-[0_0_0_1px_var(--ops-primary)]' : 'border-[var(--ops-border)] bg-[var(--ops-surface)]')}>
        <div className="flex items-start justify-between gap-3"><div><div className="text-[11px] font-extrabold uppercase tracking-[0.14em] text-[var(--ops-text-subtle)]">{label}</div><div className="mt-2 font-mono text-3xl font-extrabold leading-none">{value(data).toLocaleString('de-DE')}</div></div><span className={clsx('rounded-lg bg-[var(--ops-surface-elevated)] p-2', tone)}><Icon size={19} /></span></div>
        <div className="mt-3 flex items-center justify-between text-xs text-[var(--ops-text-muted)]"><span>{helper}</span><ArrowRight className={clsx('h-4 w-4 transition-transform', active === key ? 'translate-x-0 text-[var(--ops-primary)]' : '-translate-x-1 opacity-0 group-hover:translate-x-0 group-hover:opacity-100')} /></div>
      </button>)}
    </div>
  </ContentCard>;
}

function DetailShell({ title, subtitle, children }: { title: string; subtitle: string; children: ReactNode }) {
  return <ContentCard surface="raised" className="min-w-0 overflow-hidden xl:min-h-0 xl:flex-1"><div className="border-b border-[var(--ops-divider)] p-5"><SectionHeader title="Detailanalyse" /><h2 className="mt-2 text-2xl font-extrabold">{title}</h2><p className="mt-1 text-sm text-[var(--ops-text-muted)]">{subtitle}</p></div><div className="space-y-5 p-5 xl:max-h-full xl:overflow-y-auto">{children}</div></ContentCard>;
}

function RankedList({ rows, onOpen, valueLabel = 'Personen' }: { rows: Array<{ id: string; label: string; value: number; meta?: string }>; onOpen: (row: { id: string; label: string }) => void; valueLabel?: string }) {
  const max = Math.max(1, ...rows.map(row => row.value));
  return <div className="overflow-hidden rounded-xl border border-[var(--ops-border)]">{rows.map((row, index) => <button key={row.id} onClick={() => onOpen(row)} className="group grid w-full grid-cols-[2.5rem_1fr_auto] items-center gap-3 border-b border-[var(--ops-divider)] bg-[var(--ops-surface)] px-4 py-3 text-left last:border-0 hover:bg-[var(--ops-surface-elevated)]"><b className="font-mono text-lg text-[var(--ops-text-subtle)]">{String(index + 1).padStart(2, '0')}</b><div><div className="flex justify-between gap-3"><b>{row.label}</b><span className="text-sm font-bold">{row.value} {valueLabel}</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-[var(--ops-background)]"><div className="h-full rounded-full bg-[var(--ops-primary)]" style={{ width: `${row.value / max * 100}%` }} /></div>{row.meta && <div className="mt-1 text-xs text-[var(--ops-text-muted)]">{row.meta}</div>}</div><ArrowRight className="h-4 w-4 text-[var(--ops-primary)] transition-transform group-hover:translate-x-1" /></button>)}</div>;
}

function DetailAnalysis({ active, data }: { active: AnalyticsKey; data: AnalyticsData }) {
  const navigate = useNavigate();
  const hotelRows = data.hotels.map(hotel => ({ id: hotel.id, name: hotel.name, rooms: roomCount([hotel]), beds: bedCount([hotel]), location: hotel.location || hotel.region || 'Ohne Standort' })).sort((a, b) => b.rooms - a.rooms);
  const nationRows = [...data.athletes.reduce((map, athlete) => map.set(athlete.nationCode || '—', (map.get(athlete.nationCode || '—') || 0) + 1), new Map<string, number>())].map(([label, value]) => ({ id: label, label, value })).sort((a, b) => b.value - a.value);
  const disciplineRows = [...data.athletes.reduce((map, athlete) => { (athlete.disciplines || [athlete.discipline || '']).filter(Boolean).forEach(value => map.set(value, (map.get(value) || 0) + 1)); return map; }, new Map<string, number>())].map(([label, value]) => ({ id: label, label, value, meta: data.events.some(event => event.discipline === label) ? 'Event angelegt' : 'Noch kein Event zugeordnet' })).sort((a, b) => b.value - a.value);
  const dates = data.hotels.flatMap(h => (h.roomInventories || []).flatMap(i => [i.availableFrom.slice(0, 10), i.availableUntil.slice(0, 10)])).sort();
  const min = dates[0], max = dates.at(-1); const timeline: Array<{ date: string; rooms: number; beds: number }> = [];
  if (min && max) for (let cursor = new Date(`${min}T00:00:00Z`), end = new Date(`${max}T00:00:00Z`); cursor <= end; cursor.setUTCDate(cursor.getUTCDate() + 1)) { const iso = cursor.toISOString().slice(0, 10); const inventory = data.hotels.flatMap(h => h.roomInventories || []).filter(i => i.availableFrom.slice(0, 10) <= iso && i.availableUntil.slice(0, 10) >= iso); timeline.push({ date: cursor.toLocaleDateString('de-DE', { day: '2-digit', month: '2-digit', timeZone: 'UTC' }), rooms: inventory.reduce((s, i) => s + i.roomCount, 0), beds: inventory.reduce((s, i) => s + i.roomCount * i.roomType.maxPersons, 0) }); }

  if (active === 'hotels') return <DetailShell title="Hotels" subtitle="Kapazität je Hotel – ein Klick öffnet den operativen Hotelbereich."><div className="h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={hotelRows.slice(0, 10)} layout="vertical" margin={{ left: 20 }}><CartesianGrid stroke="var(--ops-divider)" horizontal={false} /><XAxis type="number" stroke="var(--ops-text-muted)" /><YAxis type="category" dataKey="name" width={135} tick={{ fill: 'var(--ops-text-muted)', fontSize: 11 }} /><Tooltip contentStyle={{ background: 'var(--ops-surface-elevated)', border: '1px solid var(--ops-border)' }} /><Bar dataKey="rooms" name="Zimmer" fill="var(--ops-primary)" radius={[0, 5, 5, 0]} /></BarChart></ResponsiveContainer></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="text-left text-[11px] uppercase tracking-wider text-[var(--ops-text-subtle)]"><tr><th className="p-3">Hotel</th><th>Standort</th><th>Zimmer</th><th>Betten</th><th /></tr></thead><tbody>{hotelRows.map(row => <tr key={row.id} onClick={() => navigate(`/hotels?hotelId=${row.id}`)} className="cursor-pointer border-t border-[var(--ops-divider)] hover:bg-[var(--ops-surface-elevated)]"><td className="p-3 font-bold">{row.name}</td><td>{row.location}</td><td>{row.rooms}</td><td>{row.beds}</td><td><ArrowRight size={16} className="text-[var(--ops-primary)]" /></td></tr>)}</tbody></table></div></DetailShell>;
  if (active === 'rooms' || active === 'beds') { const field = active; return <DetailShell title={active === 'rooms' ? 'Zimmer im Zeitverlauf' : 'Betten im Zeitverlauf'} subtitle="Tagesgenaue Verfügbarkeit aus den hinterlegten Hotelkontingenten.">{timeline.length ? <><div className="h-80"><ResponsiveContainer width="100%" height="100%"><AreaChart data={timeline}><defs><linearGradient id="analyticsArea" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="var(--ops-primary)" stopOpacity={0.6}/><stop offset="95%" stopColor="var(--ops-primary)" stopOpacity={0.05}/></linearGradient></defs><CartesianGrid stroke="var(--ops-divider)" vertical={false}/><XAxis dataKey="date" stroke="var(--ops-text-muted)" fontSize={11}/><YAxis stroke="var(--ops-text-muted)"/><Tooltip contentStyle={{ background: 'var(--ops-surface-elevated)', border: '1px solid var(--ops-border)' }}/><Area type="monotone" dataKey={field} name={active === 'rooms' ? 'Zimmer' : 'Betten'} stroke="var(--ops-primary)" fill="url(#analyticsArea)" strokeWidth={3}/></AreaChart></ResponsiveContainer></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{timeline.filter((_, i) => i % Math.max(1, Math.ceil(timeline.length / 6)) === 0).map(day => <div key={day.date} className="rounded-xl border border-[var(--ops-border)] bg-[var(--ops-surface)] p-3"><span className="text-xs text-[var(--ops-text-muted)]">{day.date}</span><b className="mt-1 block text-xl">{day[field]}</b></div>)}</div></> : <EmptyState title="Keine Kontingentzeiträume vorhanden" />}</DetailShell>; }
  if (active === 'nations') return <DetailShell title="Nationen" subtitle="Teilnehmende Personen nach Nation. Auswahl öffnet die vorgefilterte Athletenliste."><RankedList rows={nationRows} onOpen={row => navigate(`/athletes?nation=${encodeURIComponent(row.id)}`)} /></DetailShell>;
  if (active === 'disciplines') return <DetailShell title="Disziplinen" subtitle="Personenstärke nach Disziplin. Auswahl springt zum passenden Event."><RankedList rows={disciplineRows} onOpen={row => { const event = data.events.find(item => item.discipline === row.id); navigate(event ? `/events?eventId=${event.id}` : `/athletes?discipline=${encodeURIComponent(row.id)}`); }} /></DetailShell>;
  if (active === 'singleRooms') { const statuses = ['PENDING_APPROVAL', 'IN_QUOTA', 'APPROVED_EXTRA', 'NONE'] as const; const labels = { PENDING_APPROVAL: 'Entscheidung offen', IN_QUOTA: 'In Quote', APPROVED_EXTRA: 'Zusätzlich genehmigt', NONE: 'Kein Einzelzimmer' }; return <DetailShell title="Einzelzimmerstatus" subtitle="Statusübersicht ohne Bearbeitung – Entscheidungen erfolgen im Athletenbereich."><div className="space-y-2">{statuses.map(status => { const count = data.athletes.filter(a => a.single_room_status === status).length; return <button key={status} onClick={() => navigate(`/athletes?singleRoomStatus=${status}`)} className="flex w-full items-center justify-between rounded-xl border border-[var(--ops-border)] bg-[var(--ops-surface)] p-4 hover:bg-[var(--ops-surface-elevated)]"><span><b>{labels[status]}</b><small className="mt-1 block text-[var(--ops-text-muted)]">Athletenliste mit diesem Status öffnen</small></span><span className="flex items-center gap-3"><StatusChip tone={status === 'PENDING_APPROVAL' ? 'warning' : status === 'APPROVED_EXTRA' ? 'info' : 'neutral'}>{count}</StatusChip><ArrowRight size={17}/></span></button>})}</div></DetailShell>; }
  const tasks = data.athletes.filter(a => !a.assignment?.hasAssignment || a.hasPendingRoomlistReview || a.single_room_status === 'PENDING_APPROVAL').slice(0, 30);
  return <DetailShell title="Operative Konflikte" subtitle="Priorisierte Aufgabenliste. Jeder Eintrag führt direkt in den zuständigen Arbeitsbereich.">{tasks.length ? <div className="space-y-2">{tasks.map(athlete => { const pending = athlete.single_room_status === 'PENDING_APPROVAL'; const review = athlete.hasPendingRoomlistReview; const label = pending ? 'Einzelzimmerentscheidung offen' : review ? 'Importänderung prüfen' : 'Zimmerzuweisung fehlt'; return <button key={athlete.id} onClick={() => navigate(pending || review ? `/athletes?athleteId=${athlete.id}` : `/assignments?athleteId=${athlete.id}`)} className="group flex w-full items-center justify-between rounded-xl border border-[var(--ops-border)] bg-[var(--ops-surface)] p-4 text-left hover:border-[var(--ops-border-strong)] hover:bg-[var(--ops-surface-elevated)]"><div><div className="flex items-center gap-2"><StatusChip tone={pending ? 'warning' : review ? 'info' : 'error'}>{pending ? 'Entscheidung' : review ? 'Prüfung' : 'Zuweisung'}</StatusChip><b>{athlete.firstname} {athlete.lastname}</b></div><p className="mt-1 text-xs text-[var(--ops-text-muted)]">{athlete.nationCode} · {athlete.discipline || athlete.disciplines?.join(', ') || 'Keine Disziplin'} · {label}</p></div><ArrowRight className="text-[var(--ops-primary)] transition-transform group-hover:translate-x-1" size={18}/></button>})}</div> : <EmptyState title="Keine Konflikte" description="Aktuell besteht kein operativer Handlungsbedarf." />}</DetailShell>;
}

export function RoomAnalytics() {
  const [active, setActive] = useState<AnalyticsKey>('hotels');
  const [data, setData] = useState<AnalyticsData>({ hotels: [], events: [], athletes: [], bookings: [] });
  const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  useEffect(() => { void Promise.all([api.getHotels(), api.getEvents(), api.getAthletes(), api.getRoomAssignments()]).then(([hotels, events, athletes, bookings]) => { setData({ hotels, events, athletes, bookings }); setError(null); }).catch(() => setError('Analytics-Daten konnten nicht geladen werden.')).finally(() => setLoading(false)); }, []);
  const updated = useMemo(() => new Intl.DateTimeFormat('de-DE', { hour: '2-digit', minute: '2-digit' }).format(new Date()), [data]);
  if (loading) return <div className="flex h-64 items-center justify-center"><Loader2 className="h-8 w-8 animate-spin text-blue-600" /></div>;
  return <PageLayout className="[--ops-background:#111d2e] [--ops-surface:#1a2a40] [--ops-surface-raised:#21334c] [--ops-surface-elevated:#2a3e59] [--ops-surface-overlay:#344b67] [--ops-border:#4b6380] [--ops-divider:#405773] [--ops-text-muted:#b7c4d4] xl:flex xl:h-full xl:min-h-0 xl:flex-col xl:gap-4 xl:space-y-0">
    <PageHeader eyebrow="Operations Center" title="Analytics" subtitle="Kennzahlen verstehen, Ursachen analysieren und direkt im passenden Arbeitsbereich handeln." meta={<><StatusChip tone="success">Live-Daten</StatusChip><StatusChip tone="neutral"><CalendarRange className="mr-1 h-3 w-3" />Aktualisiert {updated} Uhr</StatusChip></>} />
    {error && <ErrorState title="Daten nicht verfügbar" description={error} />}
    <div className="flex flex-col gap-4 xl:min-h-0 xl:flex-1 xl:flex-row"><KpiNavigation active={active} data={data} onSelect={setActive} /><DetailAnalysis active={active} data={data} /></div>
  </PageLayout>;
}
