import type { ReactNode } from 'react';
import { clsx } from 'clsx';
import { ContentCard, SectionHeader, StatusChip } from './primitives';

type Tone = 'neutral' | 'primary' | 'success' | 'warning' | 'error' | 'info';

export function MetricCard({ label, value, helper, trend, tone = 'neutral' }: { label: ReactNode; value: ReactNode; helper?: ReactNode; trend?: ReactNode; tone?: Tone }) {
  return <ContentCard className="p-4"><div className="text-[11px] font-extrabold uppercase tracking-[0.14em] text-[var(--ops-text-subtle)]">{label}</div><div className="mt-3 font-mono text-[var(--ops-type-kpi-size)] font-extrabold leading-none text-[var(--ops-text)]">{value}</div><div className="mt-3 flex items-center justify-between gap-2 text-xs text-[var(--ops-text-muted)]">{helper && <span>{helper}</span>}{trend && <StatusChip tone={tone}>{trend}</StatusChip>}</div></ContentCard>;
}

export function StatusCard({ title, status, children, tone = 'neutral' }: { title: ReactNode; status: ReactNode; children?: ReactNode; tone?: Tone }) { return <ContentCard className="p-4"><SectionHeader title={title} actions={<StatusChip tone={tone}>{status}</StatusChip>} />{children && <div className="mt-4 text-sm text-[var(--ops-text-muted)]">{children}</div>}</ContentCard>; }
export function EntityCard({ title, subtitle, meta, actions, children }: { title: ReactNode; subtitle?: ReactNode; meta?: ReactNode; actions?: ReactNode; children?: ReactNode }) { return <ContentCard interactive className="p-4"><div className="flex justify-between gap-3"><div className="min-w-0"><div className="truncate font-bold text-[var(--ops-text)]">{title}</div>{subtitle && <div className="mt-1 truncate text-xs text-[var(--ops-text-muted)]">{subtitle}</div>}</div>{actions}</div>{meta && <div className="mt-3 flex flex-wrap gap-2">{meta}</div>}{children && <div className="mt-4">{children}</div>}</ContentCard>; }
export function ProgressCard({ title, value, max = 100, label }: { title: ReactNode; value: number; max?: number; label?: ReactNode }) { const percent = Math.max(0, Math.min(100, (value / max) * 100)); return <ContentCard className="p-4"><SectionHeader title={title} actions={label} /><div className="mt-4 h-2 overflow-hidden rounded-full bg-slate-900/60"><div className="h-full rounded-full bg-blue-400 transition-[width] duration-300" style={{ width: `${percent}%` }} /></div></ContentCard>; }
export function TimelineCard({ title, items }: { title: ReactNode; items: Array<{ id: string; title: ReactNode; meta?: ReactNode; tone?: Tone }> }) { return <ContentCard className="p-4"><SectionHeader title={title} /><ol className="mt-4 space-y-3">{items.map((item) => <li key={item.id} className="flex gap-3"><span className={clsx('mt-1 h-2 w-2 rounded-full', item.tone === 'warning' ? 'bg-amber-300' : item.tone === 'error' ? 'bg-rose-300' : 'bg-blue-300')} /><div className="min-w-0 text-sm"><div className="text-[var(--ops-text)]">{item.title}</div>{item.meta && <div className="text-xs text-[var(--ops-text-subtle)]">{item.meta}</div>}</div></li>)}</ol></ContentCard>; }
export function InfoCard({ title, children, actions }: { title: ReactNode; children?: ReactNode; actions?: ReactNode }) { return <ContentCard className="p-4"><SectionHeader title={title} actions={actions} />{children && <div className="mt-4 text-sm text-[var(--ops-text-muted)]">{children}</div>}</ContentCard>; }
